### ISSUE TITLE
Move all sample models to a subdirectory

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#1]
So when someone first visits the repo, they see the README.md without having to scroll down.

**Comment by lexaknyazev** [comment]
Since git doesn't actually move files, we've got two options to do that:
- simply move files to a subdirectory and lose commit history, OR
- rewrite commit history with updated path (should be safe, since we have no forks yet).

@pjcozzi What do you prefer?

**Comment by pjcozzi** [comment]
Give the rewrite a shot, fancy.

**Comment by lexaknyazev** [comment]
Considering storage of different versions, what layout will work better?

- __repo root__
  - README.md (_overall ToC_)
    - 1.0
      - (_models_)
    - 1.1
      - (_models_)
  
__OR__

- __repo root__
  - README.md (_repo description and links_)
    - 1.0
      - README.md (_dir ToC_)
      - (_models_)
    - 1.1
      - README.md (_dir ToC_)
      - (_models_)

**Comment by pjcozzi** [comment]
Up to you.

(1) has less indirection, but (2) will scale better with new versions.

**Comment by lexaknyazev** [comment]
Rewriting done, please review current repo state.

**Comment by pjcozzi** [comment]
Looks **great**!

**Comment by lexaknyazev** [comment]
I've re-pushed everything one more time. All links in all transferred commits should work now.
OK to close this?

**Comment by pjcozzi** [comment]
👍
