### ISSUE TITLE
AnimatedBox sample for MaterialsCommon is embedding buffer

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/glTF-Sample-Models#10]
The sample file contains buffer data as embedded data. That should be resolved externally.

**Comment by pjcozzi** [comment]
Thanks for the report, @kyasbal-1994!  I think this will be resolved when we finalize the sample variants approach in #4.  @lasalvavida do you agree?

**Comment by lasalvavida** [comment]
Yes! @kyasbal-1994 I will get to this as soon as I can.

**Comment by pjcozzi** [comment]
@kyasbal-1994 thanks again for the report.

This was fixed in #24 thanks to @lasalvavida.
