### ISSUE TITLE
Sample with diffuse property in KHR_materials_common with only one element

### ISSUE THREAD

**Issue by leonsal** [KhronosGroup/glTF-Sample-Models#100]
The [KHR_materials_common specification](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common) says that the `diffuse` property should be a `VEC4` or string.
This [BoxTextured](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxTextured/glTF-MaterialsCommon/BoxTextured.gltf) sample,  though, sets a `diffuse` property as an array with only one element.

**Comment by andreasplesch** [comment]
This may be a result of the extension spec. written against v.1.0 ?

**Comment by DrX3D** [comment]
Is this still a bug in the model or spec @lexaknyazev ? Default is to close within a month.

**Comment by donmccurdy** [comment]
The linked model has been removed, and the remaining BoxTextured samples are valid. I think this can be closed.

**Comment by DrX3D** [comment]
Closing this per @donmccurdy recommendation
