### ISSUE TITLE
Preview in macOS Quick Look plugin

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Models#101]
There are lots of [Quick Look plugins for macOS](https://github.com/sindresorhus/quick-look-plugins), that allow you to preview files using the spacebar. It would be very convenient to have one for glTF. Perhaps it could be done with Electron and three.js or Babylonjs? Or perhaps these plugins must be written natively, I'm not sure.

**Comment by bwasty** [comment]
I had a quick look at the [Quick Look Programming Guide](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Introduction/Introduction.html). It seems the plugin has to be native and can return for example images, COLLADA (DAE) and HTML. It's unclear if WebGL would be supported.

I wonder if my [viewer](https://github.com/bwasty/gltf-viewer) could be transformed into such a plugin. I'm already planning to add image/animated gif export to easier test all sample models at once.

**Comment by pjcozzi** [comment]
@bwasty that would be huge, please let us know if you use your viewer as a plugin!

**Comment by magicien** [comment]
I developed a QuickLook plugin for glTF.
[GLTFQuickLook](https://github.com/magicien/GLTFQuickLook)
![screenshot](https://user-images.githubusercontent.com/1047810/33096295-58d6cba0-cebb-11e7-8e52-394a3c649295.png)

**Comment by pjcozzi** [comment]
Super cool, thanks for sharing @magicien!

@donmccurdy should we still keep this open?

**Comment by donmccurdy** [comment]
Outstanding, thanks! 🎉

**Comment by Bersaelor** [comment]
@magicien GLTFQuicklook doesn't seem to work anymore, maybe it's a change in Big Sur or the Apple M1 silicon?
Are you still working on it?

**Comment by magicien** [comment]
@Bersaelor It needs to notarize the plugin. I'm going to upload a notarized zip file later.
It also works with Apple silicon. I'm checking if I can build the plugin as a universal binary.

**Comment by magicien** [comment]
I realized it's hard to notarize the QuickLook plugin. I added instructions to enable the plugin instead.

**Comment by aaronpalko** [comment]
The installation process for the QuickLook plugin has become a sort of mystery, starting with Monterey; the instructions to enable it don't seem to work anymore.
