### ISSUE TITLE
Boombox got small

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Models#102]
In #64 (f1800505462d35e57829f1d87a579d773c7c5458), an update got merged to `Boombox.gltf` that made it much smaller than it had previously been, by removing some lines that set the scale to 80.

The natural size of the Boombox geometry is [barely one centimeter](https://github.com/KhronosGroup/glTF-Sample-Models/blob/f1800505462d35e57829f1d87a579d773c7c5458/2.0/BoomBox/glTF/BoomBox.gltf#L56-L64) in any direction, which is quite small for a box that looks like it might otherwise be capable of playing CDs.

Was the size change intentional?

**Comment by bghgary** [comment]
I removed the scale since it was something I added after importing it into Unity. Since we now have source fbx assets, I didn't want some arbitrary scale added that has no corresponding source.

**Comment by emackey** [comment]
Ok.
