### ISSUE TITLE
Smiling Face does not have multiple textures

### ISSUE THREAD

**Issue by dgough** [KhronosGroup/glTF-Sample-Models#103]
The description beside the **Smiling Face** sample says:

> A smiling face with multiple textures.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#more-complex-models

However, it only has one texture. The description should be updated to say that it has one texture and vertex colors because this is the only sample with a `COLOR_0` attribute.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SmilingFace/glTF/SmilingFace.gltf#L23

**Comment by cx20** [comment]
Related: https://github.com/KhronosGroup/glTF-Sample-Models/issues/51#issuecomment-298366103

**Comment by javagl** [comment]
The model has been removed in the meantime. I assume that it's OK to close this one...
