### ISSUE TITLE
Update Sketchfab samples link

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#104]
Update https://github.com/KhronosGroup/glTF-Sample-Models#other-gltf-sample-models

with info from https://twitter.com/donrmccurdy/status/891362490147233792

via @donmccurdy

**Comment by pjcozzi** [comment]
Link to downloadable glTF models: https://sketchfab.com/models?date=week&features=downloadable&sort_by=-likeCount

**Comment by pjcozzi** [comment]
Related: https://github.com/WebVRRocks/sketchfab

**Comment by DrX3D** [comment]
@pjcozzi : Not sure what is being requested here. Please comment by 1 December or it will be closed.

**Comment by javagl** [comment]
This was about adding https://sketchfab.com/3d-models?features=downloadable&sort_by=-likeCount to the list of "Other glTF models" (which is now at https://github.com/KhronosGroup/glTF-Sample-Assets#other-gltf-models ).

On the one hand, this could be covered by the "model repository" tag in the glTF-Project-Explorer. On the other hand, there already _are_ a few entries in this list, and I think that it can make sense to have such a list prominently in the README. Other options could be to remove this list, and replace it with a link the the project explorer. (But for that, it would be nice if we could already add query parameters like `https://ecosystem.khronos.org/?tag=model-repository` to that link...)

**Comment by DrX3D** [comment]
Sample-Assets README section updated. Will be visible with the next release of the repo. No change to Sample-Models.
