### ISSUE TITLE
Broken example files?

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glTF-Sample-Models#105]
was trying to implement a parser, was using this to test:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/3a23e287d204b894425987cd1e46e68cb1861d71/2.0/BoxAnimated/glTF-Embedded/

However, my parser is finding this as an error here:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/3a23e287d204b894425987cd1e46e68cb1861d71/2.0/BoxAnimated/glTF-Embedded/BoxAnimated.gltf#L165

It says this accessor has a "count" of 576, format is 5123 (GL_UNSIGNED_SHORT), so stride should be 4 according to spec. Total length should be 576*4=2304
However, it points to bufferView 0, which has a bytelength of 1524.

Is there something I'm not understanding or the model is broken?

Thanks

**Comment by lexaknyazev** [comment]
Stride requirement is applied to vertex attributes only. That accessor contains indices, so values are tightly packed.

**Comment by reduz** [comment]
Sorry, my mistake. Forgot that in OpenGL terminology, indices are not
vertex attributes.
