### ISSUE TITLE
BoxAnimated sample is weird..

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glTF-Sample-Models#107]
at glTF-Sample-Models/2.0/BoxAnimated/

The gif shows a nice animation where box raises, spins and lowers.
Inside the .gltf file, there are two separate animations.. one for translation and another for rotation (each with individual samplers and channels).

**Comment by reduz** [comment]
oh wtf, I thought glTF supported multiple animations, but it only supports one and the channels are pretty much a cosmetic thing? I'm super disappointed...

**Comment by reduz** [comment]
feel free to close

**Comment by javagl** [comment]
It is (for me) not entirely clear what you mean. It *might* just be a matter of naming. (E.g. in my implementation, IIRC I also created one "animation" for each *channel* of a glTF animation). But maybe this can be discussed in https://github.com/KhronosGroup/glTF-Sample-Models/issues/108 in more detail, so that this specific (or rather un-specific) issue here may indeed be closed.

**Comment by reduz** [comment]
What I mean should be pretty clear if you look at the supplied [gif](
https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/BoxAnimated/screenshot/screenshot.gif).

Then take a look at the .glft file:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf#L75

Motion and rotation are two separate animations. The same issue exists with every other demo in this repository, with single animations divided in many... even including the Cesium Man walk cycle (there is one animation per bone), which is clearly wrong and against the spec itself.

**Comment by emackey** [comment]
As a test, I loaded the above file into VSCode and hand-edited the animations section, is this what you mean?

```
    "animations": [
        {
            "channels": [
                {
                    "sampler": 0,
                    "target": {
                        "node": 2,
                        "path": "rotation"
                    }
                },
                {
                    "sampler": 1,
                    "target": {
                        "node": 0,
                        "path": "translation"
                    }
                }
            ],
            "samplers": [
                {
                    "input": 6,
                    "interpolation": "LINEAR",
                    "output": 7
                },
                {
                    "input": 8,
                    "interpolation": "LINEAR",
                    "output": 9
                }
            ]
        }
    ],
```

The various WebGL-based preview engines seem to support this.  I think this is just a bug in COLLADA2GLTF ([#66](https://github.com/KhronosGroup/COLLADA2GLTF/issues/66)), writing the animation channels out separately when they should be together.
