### ISSUE TITLE
consider binary glTF using KHR-MC extension

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Models#109]
I believe the binary glTF (.glb) files are generated from glTF using gltf-pipeline, both versions 1.0 and 2.0. It further appears that default options for gltf-pipeline were used. [It would be helpful to explicitly know if this is the case].

The default for gltf-pipeline for KHR-extension using input models, I believe, is to 'optimize' output to not use the extension and include shaders instead. So the generated binary glTF files would stop using the KHR (MaterialsCommon) extension.

At least, the provided v.1.0 .glb files do not appear to use the KHR-extension, from what I could determine. I suspect the v.2.0 .glb files also do not use the KHR-extension.

For testing purposes, please consider adding a glTF-binary-MaterialsCommon version for the models which have already a glTF-MaterialsCommon version. This potentially could be automated by travis.

If there is interest, I could take a stab at this, using current glTF-pipeline with the -kmc.enable option and assuming it works correctly.

**Comment by donmccurdy** [comment]
Hi @andreasplesch, note that the `KHR_` prefix now applies to [multiple extensions](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos), and that the KHR_materials_common extension is [likely to be replaced with KHR_cmnBlinnPhong](https://github.com/KhronosGroup/glTF/issues/947). 

For glTF 2.0, there is currently no support for custom shaders at all. It is coming later, in a separate extension, but will probably not be the default from gltf-pipeline. 

So, I think that when gltf-pipeline is fully updated for glTF 2.0, and the KHR_cmnBlinnPhong extension is finalized, this will no longer be a problem. Looking at the very end of discussion on https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/272, there will be an update to gltf-pipeline soon.

**Comment by javagl** [comment]
>  For glTF 2.0, there is currently no support for custom shaders at all. It is coming later, in a separate extension, but will probably not be the default from gltf-pipeline.

Just a side note: This extension will likely be based on the glTF 1.0 ways of doing it, and will likely be available as https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_technique_webgl , but as Don said, this is **currently only a stub**.

**Comment by andreasplesch** [comment]
Thanks for the update. Since glTF 1.0 may be around for a while until 2.0 fully takes over,

**Comment by andreasplesch** [comment]
I noticed that https://github.com/KhronosGroup/glTF-Sample-Models#contributing-sample-models urges 'as many glTF variations as possible'. So if there is interest I can prepare a PR for the converted models.
