### ISSUE TITLE
Have more complex sample(s)

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF-Sample-Models#11]
Hi,

I am currently working on a plugin that converts from glTF to OSG.
All the current glTF samples are working as expected, but need to go further and ensure that the plugin is able to correctly handle more complexe cases.
Would it be possible to have more complexe samples to rely on when developping around glTF ?

One case I am thinking about could be:
Having a single bone hierarchy and several nodes (different transforms) deformed by either the full hierarchy or a subset of bones inside this hierarchy.

I tried to make such sample using 3dsMax, exporting in Collada and then converting to glTF using COLLADA2GLTF, but I don't know about how it is handled and if I can rely on it. 
For example, all the *skeletons* property are empty arrays (and fromt the glTF spec, these arrays should contain one or more nodes, right?). 
Moreover, animations are incomplete in the output, I only have times, no keyframe values, but the collada seems valid since reimporting it inside 3dsMax gives back the expected animation. 
(I am aware that 3dsMax may export data in a format that is not fully supported by other readers, so it's not clear) 

Anyway, here is my sample with both collada and gltf version:
[fries.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/630560/fries.zip)

Is there any reliable sample somewhere that I could use ? Would it be possible to have one in this repository ? 

Side question (unrelated): if several skins refers to a bone, should we expect the invBindMatrices to has the same value through the skins ? This is still not clear for me.

Sorry in advance if i missed something and thanks for your time!

**Comment by pjcozzi** [comment]
@AurL first, glTF -> OSG sounds great!  Please let us know when it is ready and we'll list it here: https://github.com/KhronosGroup/glTF#gltf-tools

Other than the sample models here, the only other source of glTF samples I know of is https://github.com/kalmykov/fr24-3d-models, but they don't have the case you mention.

If you do come up with new sample models that test new cases, please consider contributing them here, see https://github.com/KhronosGroup/glTF-Sample-Models#contributing-sample-models

**Comment by emackey** [comment]
Closing this issue in favor of various newer issues detailing needed sample models.
