### ISSUE TITLE
Where to get original models generated by COLLADA2GLTF?

### ISSUE THREAD

**Issue by fanzhanggoogle** [KhronosGroup/glTF-Sample-Models#111]
Hi @pjcozzi @lasalvavida ,

I don't know who is the right person to reach so just ask the question here.
I was wondering if the initial .dae models used to generate glTF 2.0 sample models are open to public?
I'm working on adding support for the Draco compression extension to COLLADA2GLTF. It would be nice to have the .dae models to test.

Thanks,
Fan

**Comment by lasalvavida** [comment]
Hey @fanzhanggoogle,

The source models (that we have) are available in this repo at https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels

Not every glTF 2.0 model was generated from COLLADA. I think we have fbx for some, and some were not generated by converters.

**Comment by fanzhanggoogle** [comment]
Hi @lasalvavida ,

Thanks a lot. Really appreciate the quick response!
