### ISSUE TITLE
glTF Example with Z-Fighting test?

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Sample-Models#113]
Hello. Where can I found glTF example with z-fighting test? I want check z-fight issue in my ray tracer.

**Comment by emackey** [comment]
What makes a good z-fight test, is it enough just to have some coplanar polygons of different colors?  Or do you want a sampling of nearly-coplanar stuff at different distances, as a stress test?

**Comment by capitalknew** [comment]
Both, for example, Z-fight of 3-4 coplanar polygons.

**Comment by emackey** [comment]
Sounds pretty easy to make something like this in Blender, with the glTF exporter.  Is it something that's useful to add to the sample model collection?  I'm not sure there's any standard behavior that we could expect to have similar appearance across implementations for z-fighting.

**Comment by capitalknew** [comment]
Also, possibly generate glTF by programming way? i.e. write a script for gen materials and geometry.

**Comment by bghgary** [comment]
I started a repo using the glTF-CSharp-Loader for generating test assets. I did this very quickly so there are plenty of issues to solve (e.g. the 2.0 glTF-CSharp-Loader NuGet package is not actually uploaded yet), but maybe it'll help? https://github.com/bghgary/glTF-Asset-Generator

**Comment by emackey** [comment]
Original author deleted account?

I don't think we need an official sample of Z-fighting.  With the Blender exporter today it's trivial to create one for internal testing, but I don't think it should be published.
