### ISSUE TITLE
Buggy - duplicate indexes per triangle

### ISSUE THREAD

**Issue by CentaurMare** [KhronosGroup/glTF-Sample-Models#114]
The Buggy model (from COLLADA2GLTF) is all mode 4 triangles, and as such I would expect each triangle to be composed of unique vertexes, however there are thousands of Triangles in the Buggy model which have duplicate indexes, so clearly cannot form triangles.

First few examples encountered (offset - index0 index1 index2)

123 - 2 92 2
135 - 0 94 0
144 - 95 95 96
153 - 97 98 97

**Comment by lexaknyazev** [comment]
Good catch! Looks like `2CylinderEngine` has the same issue. 
[Online version of glTF-Validator](http://github.khronos.org/glTF-Validator/) now checks uniqueness of triangle indices. CI build will follow.

@lasalvavida Could you identify the source of these errors: original COLLADA assets or converter?

**Comment by lasalvavida** [comment]
@CentaurMare are these the 1.0 or 2.0 models?

**Comment by CentaurMare** [comment]
Version 2.0 models

**Comment by javagl** [comment]
<sup>(It's hard to resist a lame pun involving the word *"buggy"* here)</sup>

From a short glance at the DAE input file, it seems like the input already contains the sequences of indices that you mentioned. I'm not deeply familiar with COLLADA2GLTF, but things like https://github.com/KhronosGroup/COLLADA2GLTF/blob/6bc66f206b63778124a7c49f25cf11041d3d5f51/helpers/geometryHelpers.cpp#L37 look like there is no reordering taking place when the input solely consists of triangles (that is: It *might* just output what already is wrong in the input file...)

**Comment by lasalvavida** [comment]
@javagl, that is the 1.0 converter source you linked, but you are correct. If the COLLADA file contains degenerate triangles the COLLADA2GLTF converter (1.0 and 2.0) doesn't correct for it. I don't think it would be too hard to add though.

I've opened up https://github.com/KhronosGroup/COLLADA2GLTF/issues/86
