### ISSUE TITLE
Move invalid models to a subdirectory or branch?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#120]
Should we move invalid glTF models such as WalkingLady (#83) and SmilingFace (?) to a separate subdirectory or branch?

Having them in the main samples area without them working in the popular engines is causing some confusion.

**Comment by donmccurdy** [comment]
+1. The relevant issue for SmilingFace is https://github.com/KhronosGroup/glTF-Sample-Models/issues/103.

Demos:

- [WalkingLady.gltf](https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WalkingLady/glTF/WalkingLady.gltf)
- [SmilingFace.gltf](https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/SmilingFace/glTF/SmilingFace.gltf)

Is there a reason to keep the broken glTF 2.0 output anywhere, until we have it fixed? I'm not sure who would need this.

**Comment by emackey** [comment]
I'm in favor of removing them.

**Comment by emadurandal** [comment]
(As an outsider opinion,) please feel free to move WalkingLady.gltf.

**Comment by pjcozzi** [comment]
> We could probably just remove the glTF 2.0 output, and keep the source and glTF 1.0 versions as-is.

Sounds good, we can add them back in #83 and #103.
