### ISSUE TITLE
Should all sample models pass validation?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#121]
Currently, some sample models generate validation warnings:
1. Models with extensions report unknown properties
2. Empty nodes
3. Degenerate triangles

For (1) should we update the validator?  For (2) and (3), should we update the models - or add a "doc fix" to the samples models repo?

CC @lexaknyazev

**Comment by lexaknyazev** [comment]
@pjcozzi 
1. Update COLLADA2GLTF. It writes those properties in the main object instead of extension object. Validator raises no more than 1 warning for each unrecognized extensions.
2. Review severity of validation issues. See: https://github.com/KhronosGroup/glTF-Validator/issues/14#issuecomment-333300340.
3. Fix & reconvert source models or implement that stage in converter or pipeline.

**Comment by pjcozzi** [comment]
1. Is there already a bug on this?
2. OK
3. We can change the models, but isn't this the same as (2) - a severity issue?

**Comment by lexaknyazev** [comment]
> Is there already a bug on this?

I don't think so. We should finalize common materials first.

> We can change the models, but isn't this the same as (2) - a severity issue?

I think the severity of that issue should be kept intact.

**Comment by DrX3D** [comment]
@pjcozzi @lexaknyazev Is this resolved. Default operation is to close this between 20 & 27 November.

**Comment by javagl** [comment]
The fact that models should _pass_ validation (without errors) has already been established and implemented as a CI check.

The fact that many models generate warnings (some of which could be avoided very easily) is something that might be tracked in a dedicated issue in the new repo. In general, the sample assets should be _good_ along as many dimensions as possible (small, efficient, well-structured, redundancy-free, as few warnings as reasonably possible...)

**Comment by DrX3D** [comment]
Closing this issue. If there is a desire to update new models, please create an issue in Sample-Assets repo.
