### ISSUE TITLE
BoxAnimated clip durations do not match.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Models#126]
1. Previewing the BoxAnimated model here: https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf
2. Open the "Animation" tab and press "playAll". (see https://github.com/KhronosGroup/glTF-Sample-Models/issues/108)

After pressing `playAll`, the two clips (position and rotation) line up for the first runthrough, but their durations are different, so after this they stop lining up. Same issue occurs in the BabylonJS sandbox. In the console I find:

![screen shot 2017-10-27 at 8 32 23 am](https://user-images.githubusercontent.com/1848368/32112453-2ec8070c-baf2-11e7-82e4-5c81f70a1f48.png)

I believe this has the same underlying cause as #108, namely that these two clips should have been a single `animations` entry, inherently with the same length, but do not.

**Comment by pjcozzi** [comment]
Sounds like a COLLADA2GLTF issue or an issue with the COLLADA exporter.  I'm pretty sure this model was authored with Modo.

**Comment by pjcozzi** [comment]
@likangning93 can you see if this model has the same animation issue you were having?

Then perhaps you can discuss with @sbtron @bghgary and others here.

**Comment by likangning93** [comment]
@pjcozzi not quite the same problem.

This is two separate animations looping asynchronously and slipping, but the problem I was discussing with @sbtron and @bghgary is what to do when looping separate channels within one animation. Babylon "wraps" when time is outside a channel's given keyframes and Three.js holds the nearest keyframe, while Cesium can do either but defaults to holding.

**Comment by likangning93** [comment]
But for what it's worth, I also think the box's animations should actually be separate channels in one `animation`, and if there was a second `animation` it'd have the smaller box do something completely different like `*gasp*` rotate along a different axis.

**Comment by pjcozzi** [comment]
Moved spec discussion to the glTF repo: https://github.com/KhronosGroup/glTF/issues/1179
