### ISSUE TITLE
Duplicated materials in buggy

### ISSUE THREAD

**Issue by vorg** [KhronosGroup/glTF-Sample-Models#128]
Buggy model have lots of duplicated materials e.g. "Material_20" is listed 63 times in the materials array. It must come from an exporter as every mesh has it's own copy. Should this sample be optimized  somehow or it's i up to loader to spot and fix the duplication?

**Comment by pjcozzi** [comment]
I think this model should be cleaned up - so it is a good learning tool.

This could be a COLLADA2GLTF issue or issue with the source COLLADA.  The 2.0 branch of gltf-pipeline should be able to remove the redundancy.

**Comment by Siccity** [comment]
Just to bring attention up this old issue again, the 2CylinderEngine also has a ton of duplicated materials.
Should importers try to merge similar materials to circumvent this issue?

**Comment by emackey** [comment]
Generally, in the glTF ecosystem, exporters, converters, and pipelines are expected to take on the responsibility of preparing the glTF as best they can for immediate rendering.

Unfortunately, no one has had time to prioritize cleaning up some of these older samples, so this bug in the sample repo is still open.  Contributions welcome, of course.  But be aware that this particular model is part of a set that were being used to test the output of COLLADA2glTF, so hand-edits to them have been rejected in the past.  The COLLADA file in the "sourceModels" folder may be the first thing that needs cleaning up.

**Comment by javagl** [comment]
An aside that comes to my mind (but that may rather be brought up as an issue in COLLADA2GLTF, if it is not already addressed) is: **Iff** the source model contains multiple instances of materials that are essentially equal, should the converter then be allowed to simply merge them into one for the glTF? 

There are at least two options
- Don't merge by default, but allow it via a command-line flag
- Don't merge at all, but leave the option to merge materials to a dedicated "optimizer" tool

In the spirit of "one tool should do one task, and it should do it *right*", the latter may be more appealing. A 1:1 correspondence between input and output probably makes things *much* simpler. Considering that there are endless other possible optimizations (e.g. simplifications of the node structure), trying to build them into a converter opens a whole can of worms...

Similarly, for generic importer libraries: They should be *very* careful when doing optimizations like merging materials. What if the materials have some sort of higher-level semantics, or are supposed to be modified at runtime?

So as emackey said: This particular issue should probably be tackled at the sourceModels level.

**Comment by DrX3D** [comment]
The models mentioned here (Buggy, 2CylinderEngine) do not have licenses that are suitable for continued use. No additional work will be done on these. This issue will be closed by 27 November.

**Comment by DrX3D** [comment]
Closed because there are no recent requests
