### ISSUE TITLE
Add link to GeoFS aircraft models

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#129]
https://github.com/geofs-plugins/aircraft-warehouse

Need to ask about terms of use.

**Comment by DrX3D** [comment]
@pjcozzi : Is there any reason or need to keep this open. The default is to close by 27 November.

**Comment by javagl** [comment]
This should be added as a `model-repository` to the project explorer. (Can be closed here, I'll take a note to add it)

**Comment by javagl** [comment]
After another look:

- It seems to only contain the _parts_ of the planes as GLB files (which are assembled via some unrelated JSON file that refers to these GLBs)
- There is no licensing information
- Most importantly: It's glTF 1.0 😬 

I'll just close this here.
