### ISSUE TITLE
BoxTextured Sample TEXCOORD_0 Accessor data for UV's

### ISSUE THREAD

**Issue by jox81** [KhronosGroup/glTF-Sample-Models#131]
In the [BoxTextured](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxTextured/glTF-Embedded/BoxTextured.gltf) Model, the accessors data seem correct for POSITION and NORMALS but why values in the TEXCOORD_0 accessor aren't in range of "max": [ 1.0, 1.0 ], "min": [ 0.0, 0.0 ] but have a "max": [ 6.0, 1.0 ] ?  

`
        {
            "bufferView": 2,
            "byteOffset": 0,
            "componentType": 5126,
            "count": 24,
            "max": [
                6.0,
                1.0
            ],
            "min": [
                0.0,
                0.0
            ],
            "type": "VEC2"
        }
`

Shouldn't those be normalized ?
Where is my misunderstanding ?

Thank u

**Comment by lexaknyazev** [comment]
Texture coordinates outside of `[0.0, 1.0]` range are supposed to be wrapped by graphics API according to `sampler.wrapS` and `sampler.wrapT` properties.

**Comment by DrX3D** [comment]
@lexaknyazev , @emackey : Has this been resolved and can be closed? Default operation is to close this between 20 & 27 November.

**Comment by DrX3D** [comment]
Closed because there are no recent requests

**Comment by javagl** [comment]
@DrX3D I didn't have this issue on the radar. It is indeed a bit ... obscure that the texture coordinates have this range. It should be an easy fix, though. If you agree, I'd transfer it to glTF-Sample-Assets (reopening it in the process)

**Comment by emackey** [comment]
@javagl Perhaps we could just take a copy of `Box With Spaces` without the spaces in the filename, and use it as BoxTextured?

**Comment by javagl** [comment]
@emackey That looks "cleaner", in this regard (it might also avoid some of the questions that are related to licensing and the logo in `BoxTextured`...).
