### ISSUE TITLE
Remove unratified extension samples from master branch

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF-Sample-Models#136]
Some 2.0 models have a samples using materials-common and webgl extensions (e.g. [Buggy](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy)). Both these extensions are not finalized. Having it in master is causing some confusion as to whether they can be used/tested against.

Should we consider removing them from master while they are still under development? They could be in another branch and move to master once they are done.

**Comment by pjcozzi** [comment]
Branch sounds good to me - whatever mirrors how we handle the spec in the main repo.

**Comment by emackey** [comment]
+1 for getting them off master.

**Comment by donmccurdy** [comment]
Created a branch and opened a PR to remove these models, #140.
