### ISSUE TITLE
GearboxAssy.glb has a camera with a rather poor projection matrix.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF-Sample-Models#14]
We shouldn't provide samples that suggest it is ok to do bad things. This is a typical case where an infinite projection matrix would be a much better choice. The model already has enough aliasing artifacts as it is.

  "cameras": {
    "default-camera": {
      "name": "default_3",
      "perspective": {
        "aspectRatio": 1,
        "yfov": 0.2632462665746327,
        "zfar": 1000000,
        "znear": 0.0499999970197677
      },
      "type": "perspective"
    }

**Comment by emackey** [comment]
No further work is being done on glTF 1.0 samples.
