### ISSUE TITLE
Add sample including multiple distinct animations

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Models#142]
From https://github.com/KhronosGroup/glTF-Sample-Models/issues/108, we should include one or more samples with multiple animations that are deliberately distinct. For example, a rigged character with run/jump/idle animations. Note that the official Blender exporter and COLLADA2GLTF are not yet capable of creating samples with multiple animations.

**Comment by iambumblehead** [comment]
This [Wolf.glb][0] has multiple animations. It is made from the [wolf files here.][1]

[0]: https://github.com/KhronosGroup/UnityGLTF/files/2358714/Wolf.glb.zip
[1]: https://free3d.com/3d-model/wolf-rigged-and-game-ready-42808.html

**Comment by donmccurdy** [comment]
Thanks! The animation cycles look good and loop cleanly, but alpha on the hair textures doesn't seem quite right:

| original | three | babylon |
|--|--|--|
|  ![screen shot 2018-09-13 at 11 00 08 pm](https://user-images.githubusercontent.com/1848368/45532411-ca3a3080-b7a8-11e8-92cb-5396411ce305.png) | ![screen shot 2018-09-13 at 10 57 50 pm](https://user-images.githubusercontent.com/1848368/45532356-9959fb80-b7a8-11e8-8729-8ebda0ea2ff6.png) | ![screen shot 2018-09-13 at 10 57 46 pm](https://user-images.githubusercontent.com/1848368/45532359-9b23bf00-b7a8-11e8-849c-fce5e9a13f6f.png) |

**Comment by iambumblehead** [comment]
I sent the author of this model a link to this issue and have asked him for his advice in regards to solving the alpha.

**Comment by iambumblehead** [comment]
The artist advised me to convert the fur alpha mask texture to a png with alpha channel. I am not a 3D artist but I'll try to do it.

**Comment by iambumblehead** [comment]
<img width="1497" alt="screen shot 2018-09-15 at 2 02 13 pm" src="https://user-images.githubusercontent.com/2058705/45590579-117f0900-b8f0-11e8-804f-375b41afdcda.png">
I'm able to edit the model's gltf format using the visual studio plugin seen in the screenshot. When the fur material is modified to reference the same material used by the teeth, the fur is always white in Babylon.js and Three.js. @donmccurdy what do you think?

**Comment by donmccurdy** [comment]
I think it would need to look very close to the original, to use it as a sample. That may not be possible, unfortunately — I think the hair is meant to have both alpha mask and transparency, which glTF doesn't currently support (and may cause issues for some renderers anyway).

**Comment by prideout** [comment]
Note that the existing `InterpolationTest` model contains multiple animations, each with a nice human-readable name.  So technically maybe this issue could be closed, although it would be nice to have this with a rigged & skinned character.

**Comment by donmccurdy** [comment]
Good point – I think I'd prefer to keep this open, since the `InterpolationTest` model leaves some ambiguity on whether the animations are distinct – the screenshot has all animations playing simultaneously, which is totally reasonable in that case. A skinned character like [this robot](https://threejs.org/examples/?q=anim#webgl_animation_skinning_morph) would be better because it's very clear that animations are distinct – the result is broken if you try to play everything together.

**Comment by emackey** [comment]
Can this be considered fixed by #249?
