### ISSUE TITLE
BoxInterleaved/pbrSpecularGlossiness sample is missing pbrSG data on material

### ISSUE THREAD

**Issue by cwelman** [KhronosGroup/glTF-Sample-Models#144]
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxInterleaved/glTF-pbrSpecularGlossiness/BoxInterleaved.gltf

This file has "extensionsRequired": [ "KHR_materials_pbrSpecularGlossiness"], but the only material does not reference that extension.

This seems like a bug.  At least the expected behavior is unclear when an asset says an extension is 'Used' and 'Required', but then never uses it.

**Comment by DrX3D** [comment]
@emackey : Does this need to be resolved or can it be closed? Default operation is to close this between 20 & 27 November.

**Comment by bghgary** [comment]
Given that `pbrSpecularGlossiness` extension is archived and all variants with this extension (including this one) has been removed, it's probably safe to close.

**Comment by DrX3D** [comment]
Closed per recommendation fro @bghgary .
