### ISSUE TITLE
glTF-Draco JOINT attributes decoded as float, should be int

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Models#147]
From https://github.com/FrankGalligan/glTF-Sample-Models/issues/2 —

> See KhronosGroup#145
for reference.
> 
> In RiggedFigure:
https://github.com/FrankGalligan/glTF-Sample-Models/tree/be470ea72ecb7adf2b30932349d1b12164af07b7/2.0/RiggedFigure/glTF-Draco
> 
> The draco decoded data is returning floats, when original data is unsigned short.
> 
> The draco gltf says the JOINTS_0 data should be unsigned int:
> 
> https://github.com/FrankGalligan/glTF-Sample-Models/blob/be470ea72ecb7adf2b30932349d1b12164af07b7/2.0/RiggedFigure/glTF-Draco/RiggedFigure.gltf#L2481

**Comment by FrankGalligan** [comment]
[output_RF_comp_int.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/1965965/output_RF_comp_int.zip)
@donmccurdy Can you try this model in your viewer? The compressed JOINTS_0 attribute is set to componentType 5123.

**Comment by FrankGalligan** [comment]
@lilleyse Fixed this here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/commit/5bcd878adb9a118f239abe24e5b95acef3548146

I think this can be closed now.

**Comment by najadojo** [comment]
@FrankGalligan in the output_RF_comp_int.zip you attached above the POSITION accessor (80) has a count == 370 but Draco decoding is telling me that num_points() == 367. Why are these different? And (more of a spec question) if this is allowed why have an accessor at all for this attribute if it doesn't provide accurate data?

**Comment by donmccurdy** [comment]
From the current spec I would certainly assume `count` is expected to be correct for both compressed and uncompressed (if fallback is used) attributes. Loaders must also rely on the accessor definition for reliable type information: the Draco decoder does not know the type of each attribute from the bufferView alone, as far as I can tell.

If any of that is incorrect, the spec should likely be clarified.

**Comment by FrankGalligan** [comment]
@donmccurdy so the count can be different for compressed and uncompressed meshes. But the count for compressed meshes we can get from the Draco decompressed mesh. So I'm proposing making this change to the spec:
https://github.com/KhronosGroup/glTF/pull/1343

I also made a change to gltf-pipeline to output compressed and uncompressed fallback meshes here:
https://github.com/FrankGalligan/gltf-pipeline/tree/add_uncompressed_fallback

**Comment by donmccurdy** [comment]
I think the extension spec should be explicit about each of the accessor properties, in that case — if `count` and `bufferView` are to be ignored, what about `min` and `max`? Currently THREE.GLTFLoader relies on `componentType` to decode attributes as the correct type, but is that information also in the Draco bufferview somewhere, or would it ever change with encoding?

**Comment by najadojo** [comment]
Draco does have its own metadata that provides that information in its bufferView. It seems during compression the bitstream can change the type of the vertex buffer as an option to the pipeline. 

I suggest we make clear in the extension that count, min, max, componentType and type are all correct in the accessor and match the data that draco would report from its bufferview decoding.

**Comment by lexaknyazev** [comment]
Regarding `min`/`max`. The main spec has a note that when `accessor.bufferView` is undefined `min`/`max` still represent correct bounds of data.

I would agree with @najadojo that when fallback is present it should be filled with decompressed data instead of uncompressed data. In that case all properties will match in both versions.

**Comment by donmccurdy** [comment]
> ... when fallback is present it should be filled with decompressed data instead of uncompressed data. In that case all properties will match in both versions.

Oh, I'd missed that  distinction between decompressed and uncompressed. Yes, having `count` be correct for both versions seems preferable.

> Draco does have its own metadata that provides that information in its bufferView. It seems during compression the bitstream can change the type of the vertex buffer as an option to the pipeline.

Hm, assuming most users of the Draco extension are going to want to just use the encoder/decoder tools and not read the bitstream spec, where would they find that information? I'm not aware of API docs or an example that would give that info. Using [THREE.DRACOLoader](https://github.com/google/draco/blob/master/javascript/example/DRACOLoader.js) as a reference, I would assume the user of the decoder must know from an external source.

**Comment by lexaknyazev** [comment]
> where would they find that information

Assuming that glTF properties are correct, loaders don't need to care about bitstream. Otherwise, they should be able to get all metadata from the decoder API (see [IDL](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl)).

**Comment by donmccurdy** [comment]
Thanks — I see the `attribute.data_type()` method in that IDL file, but wasn't aware of it before. I'm still not sure what to do with its output: I can't find the enum in the IDL file or in the generated JS to compare against, or any examples of doing so, only [here](https://github.com/google/draco/blob/4b2788bb5644c142c2801e7e27420f88abde0aff/src/draco/core/draco_types.h#L25-L40) in the C++.

Up until [quite recently](https://github.com/mrdoob/three.js/pull/14002) three.js assumed _all_ draco attributes were float32 — we now rely on the accessor componentType. It [appears that BabylonJS still assumes float32](https://github.com/BabylonJS/Babylon.js/blob/3bad77f10f02c7b2a5b9f76d2c804984d848b658/src/Mesh/Compression/babylon.dracoCompression.ts#L179-L194).

**Comment by lexaknyazev** [comment]
> I can't find the enum in the IDL file

Here they are: 
https://github.com/google/draco/blob/master/src/draco/core/draco_types.h

**Comment by najadojo** [comment]
Actually looking closer even if I had a guarantee from the accessor I'd still have to copy value by value because of the Point indices map.

**Comment by lexaknyazev** [comment]
> even if I had a guarantee from the accessor I'd still have to copy value by value 

Does it mean that you won't care about `accessor.count` anyway? I'd still prefer them to be correct mainly because of VAO / command buffer predictability.

**Comment by najadojo** [comment]
No I still care very much. The whether or not the points are mapped or can be copied at once I still want to build our vertex buffers first. Doing that one way is best.

**Comment by FrankGalligan** [comment]
So we can change the spec to say that the glTF accessor properties must match the decompressed data.

E.g. in RiggedFigure then we would put "367" in the "accessor.count" For both cases where there was uncompressed fallback and when there wasn't. 

What about using the uncompressed fallback which has 370? Is this fine for loaders?

**Comment by najadojo** [comment]
No it wouldn't be if the fallback didn't contain 370 elements it wouldn't load. The compression pipeline should replace the input data with uncompressed data in the output so that the values would match.

**Comment by FrankGalligan** [comment]
Ahh got it. Yes that should work. I'm fine with that. Sound good to everyone else?

**Comment by bghgary** [comment]
> It appears that BabylonJS still assumes float32.

Yes, this is true. We can update it once the issues have converged. I've created an [BabylonJS issue](https://github.com/BabylonJS/Babylon.js/issues/4350) for this.

**Comment by FrankGalligan** [comment]
I changed the PR for the spec to try and capture what we have been talking about. https://github.com/KhronosGroup/glTF/pull/1343

Any comments? Should I add more detail?

**Comment by FrankGalligan** [comment]
Currently I have 2 PRs related to this and gltf-pipeline. Once the text lands in the extension spec, I will start making PRs to gltf-pipeline main repo.

Replace accessor properties with decompressed properties:
https://github.com/FrankGalligan/gltf-pipeline/tree/replace_original_with_decompressed

Add support for decompressed data fallback:
https://github.com/FrankGalligan/gltf-pipeline/tree/rebase_uncompressed_fallback

**Comment by FrankGalligan** [comment]
I think this was fixed a while ago. Can we close?
