### ISSUE TITLE
BrainStem.glb sets up uniforms that are never used and does not list used extensions.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF-Sample-Models#15]
The uniforms "u_ambient", "u_jointMat" and "u_specular" are setup but never used.

The model doesn't list "KHR_binary_glTF"

"extensionsUsed": [ ],

**Comment by javagl** [comment]
The `u_jointMat` *should* be used, and, as far as I can see, it *is* used, as far as I can tell. 

Also, as you stated, the GLB does not seem declare `KHR_binary_glTF`, but instead it declares `KHR_materials_common`, although this actually does *not* seem to be used - maybe just a minor bug at the point where the extensions are written? It does not seem to appear in other GLBs, though... (I checked a few, but not all of them).

**Comment by mre4ce** [comment]
Sorry, I accidentally copied "u_jointMat" in there because I was auto-converting the shader to use uniform buffers. I get there's some desire to use GLSL 1.00 but not having uniform buffers is both very limiting and not performant. Anyway, that's a different problem ;)

Yeh, we should fix-up the extensions used listed by this model. I'm not sure anyway ever checks but as a sample model it better be correct ;)

**Comment by javagl** [comment]
The BrainStem GLB seems to be a bit out-dated as well: It still contains an (unused and no longer supported) `"disable":[]` entry in `technique0` (But note that this does *not* appear in the non-binary version). Most likely this will be fixed when the sample models are re-generated in https://github.com/KhronosGroup/glTF-Sample-Models/issues/5 , @lasalvavida

**Comment by pjcozzi** [comment]
Fixed in #22 by @lasalvavida
