### ISSUE TITLE
Models using spec/gloss materials are too glossy.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Sample-Models#151]
I feel like this has been discussed somewhere but I can't recall where, so filing here.

Models using spec/gloss appear too glossy:

| default | spec/gloss |
|--|--|
| <img width="407" alt="screen shot 2018-03-08 at 10 54 37 am" src="https://user-images.githubusercontent.com/1848368/37170510-dbcac6da-22bf-11e8-9aa1-229765bef02c.png"> | <img width="457" alt="screen shot 2018-03-08 at 10 54 32 am" src="https://user-images.githubusercontent.com/1848368/37170521-e00ab0e8-22bf-11e8-957c-b9df8ac22852.png"> |

Problem appears in both threejs and babylonjs. Most likely related to conversion in COLLADA2GLTF?

**Comment by bghgary** [comment]
Yeah, https://github.com/KhronosGroup/glTF-Sample-Models/pull/76. There are a bunch of issues with the spec/gloss models.

**Comment by donmccurdy** [comment]
Ok thanks, filed https://github.com/KhronosGroup/COLLADA2GLTF/issues/156 but will leave this issue open for those using these models to test.

**Comment by bghgary** [comment]
Should we remove these models from the repo like we did for other models that are not correct?

**Comment by donmccurdy** [comment]
I don't have bandwidth to look into COLLADA2GLTF right now unfortunately, so unless someone else is planning to, yeah probably better to remove these models.

**Comment by emackey** [comment]
This can be closed now, right?

**Comment by bghgary** [comment]
I say so. We can always reopen if we need to.
