### ISSUE TITLE
BarramundiFish alpha

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Models#153]
The basecolor texture of BarramundiFish has nice transparent fins but there is no corresponding Alphamode: blend in the glTF material. The default is opaque and so the fins are rendered opaque.

If there is no other Alphamode: blend example, the fish would be a good candidate.

**Comment by bghgary** [comment]
I'm about to upload a model that has blend. You can also look at the asset generator project for [assets with blend](https://github.com/bghgary/glTF-Asset-Generator/tree/master/Output/Material_AlphaBlend) if you are testing your implementation.

**Comment by andreasplesch** [comment]
Ok. In this case, BarramundiFish would be a test for an implementation if its default Alphamode value is opaque and if it has the correct effect, eg. ignoring the texture/factor alpha for rendering.
On the other hand, the fish looks quite a bit better with the intended transparency of the fins. But any changes to an established sample model may be considered disruptive ?

**Comment by bghgary** [comment]
I'm more concerned with having to split the mesh into parts in order to get the alpha blended part to sort correctly. That will take some time.

**Comment by andreasplesch** [comment]
https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=tutorialModels&model=BarramundiFish&scale=5&type=glTF
is how currently an implementation renders which incorrectly does not consider Alphamode. So I am not sure if splitting the mesh is really required.
Anyways, no need to do anything, really.

**Comment by bghgary** [comment]
> https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=tutorialModels&model=BarramundiFish&scale=5&type=glTF

It depends if depth-write is on or off. This one has depth-write on, which has its own issues. glTF doesn't dictate depth writing or sorting behavior. See implementation note for [Alpha Coverage](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#alpha-coverage).

**Comment by andreasplesch** [comment]
Good point, alpha is hard for an engine. Would then providing more rather than less blend examples be really appropriate, to expose specific engine behavior ?

**Comment by emackey** [comment]
Actually I'm planning to author a new alpha blend test model in the next couple of days.  Stay tuned.

**Comment by bghgary** [comment]
If you are trying to make sure your implementation is covering all aspects of the spec, use the assets from the [asset generator ](https://github.com/bghgary/glTF-Asset-Generator) that I mentioned earlier. Each asset from there is isolated to an individual feature as much as possible. Increasing coverage in this repo like what @emackey is doing is also great.
