### ISSUE TITLE
Documentation of camera position

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF-Sample-Models#158]
The samples are a fantastic way to build a renderer and really kick the tires - but there's a slight hiccup in trying to compare with the reference images, since there's no camera information baked in.

It makes sense that there wouldn't be one single camera - as the different models should be viewed from different angles in order to see the facets in the best way possible, and it also makes sense to _not_ burn in a camera into the gltf itself (especially with the more unit-testy models).

@donmccurdy pointed out that the asset generator at https://github.com/bghgary/glTF-Asset-Generator creates a manifest with camera positions.

Is this something that can be provided with the existing models - or perhaps a couple pointer notes next to the references (even just point of origin, with an assumed "lookAt" at [0,0,0] and then one can fiddle with fov etc.)?

**Comment by emackey** [comment]
It's not just the camera that's different.  Different screenshots were taken in different engines with different light sources, some with HDR environments, others with just cube map environments for IBL, potentially different camera FOV, etc.  While glTF strives for a consistent look, it still must offer enough flexibility to be portable across a wide array of platforms, hardware, and rendering techniques.

I'd agree that the Asset Generator is what people should use for reference images.  The images in this repo are just a smattering of screenshots by assorted contributors, they are not "reference" images by any stretch.

However, this repo does contain a set of [Feature Test Models](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/README.md#feature-test-models) (Disclaimer, most are mine).  These models perform various tests of individual glTF features, and most of them have a README explaining how to read and use the test to see if a particular feature was implemented correctly in a given engine.

**Comment by dakom** [comment]
Ah, thanks for the explanation! Closing this for now :)

**Comment by bghgary** [comment]
We should avoid calling the images from the asset generator "reference images". We explicitly call them sample images because we use BabylonJS to generate them and it is not necessarily how every engine should look. The images are there to give more context as to what the asset should look like.

**Comment by dakom** [comment]
Thanks @bghgary - I updated the original comment to reflect that, in case anyone else stumbles on it
