### ISSUE TITLE
NormalTangentMirrorTest help

### ISSUE THREAD

**Issue by revolucas** [KhronosGroup/glTF-Sample-Models#160]
https://imgur.com/a/0yUVP

The documentation has some explanations on common issues, but this is the issue I'm having. Would anyone happen to know, just by looking at my provided image, on what could be wrong? There seems to be strange artifacting and U and V mirrors seem out-of-whack.

I'm using the glTF pbr shaders provided by this group in SDL2 and OpenGL 3.3. I also provided a screenshot of what the DamagedHelmet looks like in the engine.

**Comment by emackey** [comment]
Are you loading tangents as `vec4` from the glTF model?  What happens to the `.w` component of the loaded tangent vectors?

**Comment by revolucas** [comment]
I'm using Assimp to import the meshes, which does not read tangent as a quaternion, but a vec3. I wasn't aware of this, I believe this is an issue on their end. Thanks.

**Comment by emackey** [comment]
That's likely the main problem.  Tangent is not a quaternion, though.  The 4th component indicates handedness:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes (near the bottom, just above morph targets)

```
bitangent = cross(normal, tangent.xyz) * tangent.w
```

The `w` component is 1.0 or -1.0.  Geometry that has been mirrored (after UV/normal map baking) may have -1.0 here.
