### ISSUE TITLE
Samples publicly hosted on a server?

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Sample-Models#161]
Less an issue, more a request/question:

Is there a server where the demo files are publicly hosted for testing?

Referencing to the raw files at github doensn't work, because of github's HTTP cross origin policy (no wildcard entry Access-Control-Allow-Origin in CORS-header). Here's an example URL I tested negatively:
https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Duck/glTF-Binary/Duck.glb

Or maybe it's just a github setting? Maybe github pages supports this?

Would be great,
thanks!

**Comment by atteneder** [comment]
Indeed, that works like a charm.
I presume it'll also work with the glTF-Asset-Generator stuff.. maybe test that later.
Thanks a lot for the quick answer!

**Comment by bghgary** [comment]
> it'll also work with the glTF-Asset-Generator stuff

Yes, it should work with asset generator files also. Using https://raw.githubusercontent.com is fine for one-off testing. I would caution using it for automated testing as I don't think GitHub has any guarantees and the content can change without notice. For automated testing, I would put the [versioned assets](https://github.com/bghgary/glTF-Asset-Generator/releases) in your own repo or host them somewhere for your own purpose. In the future, we might host the versioned assets somewhere in the future for everyone to use.

**Comment by donmccurdy** [comment]
> I would caution using it for automated testing as I don't think GitHub has any guarantees and the content can change without notice

We could fix the "could change without notice" part by adding Git tags periodically. But if we're going to do that perhaps hosting versions assets some other way is just as well.

**Comment by bghgary** [comment]
> adding Git tags periodically

True. We do this for asset generator (e.g. https://raw.githubusercontent.com/bghgary/glTF-Asset-Generator/v0.5.0/Output/Material/Material_00.gltf)
