### ISSUE TITLE
Sample STEP animation

### ISSUE THREAD

**Issue by CentaurMare** [KhronosGroup/glTF-Sample-Models#162]
OK, struggled with the 'Pull Request' thingy, so raising this as an issue, sorry.

I've created a little C# application that creates a glTF TV model with animated screen from a supplied GIF file... 
[television.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/1914945/television.zip)

I tried uploading to Sketchfab but their viewer doesn't work properly, it seems to replace STEP with LINEAR.

I'm not sure if the GIF used for this particular example is royalty free, so upload a GIF (try to find one with width of twice the height) and I can convert it into a TV for a sample model if required.

**Comment by emackey** [comment]
Your list of nodes is invalid, it lists the same node multiple times in the same scene.  The validator flags this as an error.

```
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0,
        20,
        20,
        20,
        20,
        20,
        20
      ]
    }
  ],
```

**Comment by CentaurMare** [comment]
Oops, that was an issue with model combination, fixed it. Thanks for catching it.
[television.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/1917004/television.zip)

**Comment by emackey** [comment]
Thanks, but I think I'll close this in favor of the [Interpolation Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest).
