### ISSUE TITLE
An erroneous type of uinform variable exists in the fragment shader of BoxSemantics of glTF 1.0

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/glTF-Sample-Models#163]
I saw a report of glTF 1.0 model error on Twitter and post it.
The following two uniform variables of [BoxSemantics 0FS.glsl](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/BoxSemantics/glTF/BoxSemantics0FS.glsl) should be correctly `mat3`, as `mat4` is assumed to be erroneous.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/BoxSemantics/glTF/BoxSemantics.gltf#L439-L446
```js
        "nodeModelInverseTransposeMatrix": {
          "semantic": "MODELINVERSETRANSPOSE",
          "type": 35675 // FLOAT_MAT3
        },
        "nodeModelViewInverseTransposeMatrix": {
          "semantic": "MODELVIEWINVERSETRANSPOSE",
          "type": 35675 // FLOAT_MAT3
        },
```

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/BoxSemantics/glTF/BoxSemantics0FS.glsl#L30-L31
```glsl
//uniform mat4 u_nodeModelInverseTransposeMatrix;
//uniform mat4 u_nodeModelViewInverseTransposeMatrix;
uniform mat3 u_nodeModelInverseTransposeMatrix;
uniform mat3 u_nodeModelViewInverseTransposeMatrix;
```

Related: https://twitter.com/degarasu/status/985375323666579457

**Comment by DrX3D** [comment]
Thank you @cx20 for reporting this. Khronos is no longer supporting glTF 1.0. Unless there is an absolutely compelling need to fix this, this issue will be closed by 27 November.

**Comment by DrX3D** [comment]
No response to request.
