### ISSUE TITLE
BrainStem Bone root error

### ISSUE THREAD

**Issue by PsycoTodd** [KhronosGroup/glTF-Sample-Models#164]
Hello, just notice that the dancing robot's skin section, the skeleton is 2 but it should indicates the id for the root, which is 3.

**Comment by andreasplesch** [comment]
Well, node 3 is a child of node 2. So why could root not be node 2 ?

**Comment by DrX3D** [comment]
This issue needs a respsonse to @andreasplesch question. It will be closed by 1 December unless otherwise instructed.

**Comment by andreasplesch** [comment]
Yes, please feel free to close.
