### ISSUE TITLE
The sample models should all have a scene property

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Sample-Models#166]
As reported in https://github.com/KhronosGroup/glTF/issues/1326 , some of the models (particularly the hand-crafted `Simple...` models) may not have a `scene` property. According to the 2.0 spec, this means that nothing has to be rendered at all. (This was not yet entirely clear in 1.0). 

The corresponding samples should be reviewed and updated accordingly.

**Comment by emackey** [comment]
We should probably also have a sample that has multiple scenes, to test what that does in various engines.

**Comment by javagl** [comment]
Agreed. There had been some trouble with some glTF 1.0 viewers when there was no default `scene` (crashes and bugs). But I think that even more viewers (1.0 and 2.0) would bail out when there are *multiple* scenes. I'll try to create such a model as well, that could show some interesting effects ;-)

**Comment by javagl** [comment]
Closed via https://github.com/KhronosGroup/glTF-Sample-Models/pull/242 .

The point of having *multiple* scenes in one asset is currently discussed in https://github.com/KhronosGroup/glTF/issues/1542 (shortly before I was pointed to that issue, I created a simple `MultipleScenes` example that currently only is in a branch at https://github.com/javagl/glTF-Sample-Models/tree/MultipleScenes )
