### ISSUE TITLE
normal or tangent data in morph target examples

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/glTF-Sample-Models#170]
The morph target examples from #58 are very misleading trying to implement/test because it includes `NORMAL` and `TANGENT` data that are all zero. I did an octal dump of the [binaries](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.bin) [files](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphSphere/glTF/AnimatedMorphSphere.bin) and checked and sure enough I was seeing values like `0, 0, -0` as the vec3 as well as when I printed out the values in my program.

While this is still a *valid* glTF file its misleading because the lighting in the screenshots of the [gifs](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/screenshot/screenshot.gif) [shown](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphSphere/screenshot/screenshot.gif) in the README are not using the `NORMAL` and `TANGENT` data for lighting. This is more of an issue of not being to have a glTF 2.0 model to test morph target lighting (like specular, phong, normal mapping, etc.) with in this repo then.

**EDIT** I realized now that loading the model includes no point lighting built in, but guess I was implictly thinking that the morph target normals would mean it was capable of adding point lighting in

----

Looking at [`"NORMAL": 6`](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf#L228) for the `angle` morph in the cube example

which is [`"bufferView": 6`](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf#L63)

looking at the only buffer at an offset of [`"byteOffset": 1824`](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf#L175)

and 1824 bytes being `0o3440`

`od -f AnimatedMorphCube.bin`

```
0003440               0               0              -0               0
0003460               0              -0               0               0
0003500              -0               0               0              -0
0003520               0               0              -0               0
0003540               0              -0               0               0
0003560              -0               0               0              -0
0003600               0               0              -0               0
0003620               0              -0               0               0
0003640              -0               0               0              -0
0003660               0               0              -0               0
0003700               0              -0               0               0
0003720              -0               0               0              -0
0003740               0               0              -0               0
0003760               0              -0               0               0
0004000              -0               0               0              -0
0004020               0               0              -0               0
0004040               0              -0               0               0
0004060              -0               0               0              -0
0004100               0               0              -0               0
0004120               0              -0               0               0
0004140              -0               0               0              -0
0004160               0               0              -0               0
```

**Comment by sjfricke** [comment]
Thinking about it more, a good solution would be to add normals to the cube and sphere examples and then make two more samples with 4 `POSITION` and 4 `NORMAL` and one with 8 `POSITION`

This would allow conformant clients to test on this model set according to the glTF 2.0 spec

> Implementation note: The number of morph targets is not limited in glTF. A conformant client implementation must support at least eight morphed attributes. This means that it has to support at least eight morph targets that contain a POSITION attribute, or four morph targets that contain a POSITION and a NORMAL attribute, or two morph targets that contain POSITION, NORMAL and TANGENT attributes. For assets that contain a higher number of morphed attributes, renderers may choose to either fully support them (for example, by performing the morph computations in software), or to only use the eight attributes of the morph targets with the highest weights.

Would be happy to contruct the two other samples if wanted

**Comment by bghgary** [comment]
> The morph target examples from #58 are very misleading trying to implement/test because it includes NORMAL and TANGENT data that are all zero

This was not intentional. I can update them to include non-zero data.

**Comment by sjfricke** [comment]
That would be awesome if it's not too much trouble. Is there a desire for an 8 Position morph target to have on sample for testing the 8 targets requirement?

**Comment by bghgary** [comment]
> That would be awesome if it's not too much trouble

I can easily update the AnimatedMorphCube, but it appears the AnimatedMorphSphere is not a very good model as it actually inverts the vertices during the morph. Fixing the normals makes it look like a broken model. If it's not too much of a rush, we are planning on adding a model to showcase morph targets that will be more visually pleasing.

> Is there a desire for an 8 Position morph target to have on sample for testing the 8 targets requirement?

This kind of test makes more sense as an unit test model. The [asset generator project](https://github.com/bghgary/glTF-Asset-Generator) is currently generating a good set of these. Once we get to morph targets, we will certainly add tests for this.

**Comment by prideout** [comment]
Currently, `AnimatedMorphCube` seems to have VEC3 tangents but the spec says that tangents must be VEC4.

**Comment by lexaknyazev** [comment]
@prideout 
The base `TANGENT` data is `VEC4`. Morph deltas are `VEC3` (i.e. they cannot change the sign).

**Comment by donmccurdy** [comment]
Agreed that the sign shouldn't change during morphing, but, is omitting the sign part of the spec? I could just have easily assumed that the model would be required to include a 4th component with matching sign values. 

Aside — do engines support morph tangents? We do not in three.js. In samples users have provided, the morph normals are sometimes useful, sometimes not, and I've never seen a real use case that required morph tangents.


>  Is there a desire for an 8 Position morph target to have on sample for testing the 8 targets requirement?

@emackey added a nice example of this in https://github.com/KhronosGroup/glTF-Sample-Models/pull/290. It does include normals, but not tangents.

**Comment by lexaknyazev** [comment]
> is omitting the sign part of the spec?

The spec is clear on that:

> ![image](https://user-images.githubusercontent.com/3479527/110830961-35e6b100-82b3-11eb-95ba-2a0fe01c90da.png)

**Comment by bghgary** [comment]
> do engines support morph tangents?

Babylon.js supports it.

> In samples users have provided, the morph normals are sometimes useful, sometimes not, and I've never seen a real use case that required morph tangents.

I don't explicitly remember seeing one that has this, but this should be similar to a mesh not having tangents. If the computed mesh tangents are not reliable in some cases, then morphed mesh tangents will not be either.

**Comment by donmccurdy** [comment]
I would expect it to be more narrowly applicable than that. If an engine has static vertex tangents, but not morph tangents, it wouldn't fall back to pixel shader derivatives. The base vertex tangents are already relative to the base vertex normals, and exist to define the tangent space in which the normal map was baked. The normal map cannot change when morph target weights increase, and so base tangents remain consistent with the normal map even as the vertex normals are deformed.

I'm willing to believe we could create a test case that isolates the issue, but I don't think it's a practical concern, and in any engine subject to morph attribute limits (typically 4-8) I don't think it would be wise to prioritize morph tangents over additional position or normal attributes.

**Comment by emackey** [comment]
> ...and so base tangents might as well remain consistent with the normal map.

I don't think so.  The tangent vector helps establish the TBN axes in model space.  If the model morphs such that a localized part twists or rotates about its own surface normal, the tangent must change.

**Comment by donmccurdy** [comment]
Hm, that seems more plausible yes. I tried a quick test, creating a morph target that rotates NormalTangentTest around its forward-facing axis. Blender doesn't write morph tangents (not sure how we'd implement that?) but you can certainly see that things don't "just work" without them:

[NormalTangentMorphTest.glb.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/6126551/NormalTangentMorphTest.glb.zip)

| three.js | babylon.js |
|---|---|
| ![Screen Shot 2021-03-11 at 3 47 53 PM](https://user-images.githubusercontent.com/1848368/110870396-323a3680-8281-11eb-8fff-4d9157eb707f.png) | ![Screen Shot 2021-03-11 at 3 48 03 PM](https://user-images.githubusercontent.com/1848368/110870398-32d2cd00-8281-11eb-8915-7aca2bab42d2.png) |

**Comment by DrX3D** [comment]
@donmccurdy @emackey @bghgary @lexaknyazev : Is there more work to do on this issue? Should it be closed or moved to [glTF-Sample-Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) repo? Default is to close by 27 November.

**Comment by donmccurdy** [comment]
No preference on my side. three.js has not implemented morph tangents; we haven't had users file issues or feature requests that require it. But Blender does support exporting morph tangents now, so a sample would be less difficult to create.

**Comment by bghgary** [comment]
Like @donmccurdy, I haven't seen anyone try to use this feature either. If we transfer it, it should be low priority.

**Comment by DrX3D** [comment]
Closing this issue because it needs justification for work to be done. If there is a desire to have this feature, please open an issue (or request transferring this one) to Sample-Assets.
