### ISSUE TITLE
Waterbottle.glb is incorrect

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF-Sample-Models#179]
The gltf-binary version waterbottle is incorrect and has different material textures compared to the rest of the variations like glTF etc.

**Comment by cx20** [comment]
I compared the models of `glTF` and g`lTF-Binary` and confirmed that the display results are different.
The right side seems to have less gloss.

|Waterbottle.gltf |Waterbottle.glb|
|:-----:|:-----:|
|[![image](https://user-images.githubusercontent.com/1833979/42096024-42dd3258-7bef-11e8-966a-c08693b2486c.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=WaterBottle&scale=10&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/42096036-479b74c6-7bef-11e8-83d9-73e8a1f9441f.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=WaterBottle&scale=10&type=glTF-Binary)|
|[![image](https://user-images.githubusercontent.com/1833979/42096048-4b9fe854-7bef-11e8-982c-cf480be07eb6.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=WaterBottle&scale=10&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/42096056-4fce0186-7bef-11e8-8bc4-2b03c9305f2a.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=WaterBottle&scale=10&type=glTF-Binary)|

Is this a problem with `glTF Tools for Unity`, not `COLLADA2GLTF`?
I'd like to test it again once the model has been modified.

**Comment by bghgary** [comment]
Most likely I screwed up when exporting the file.

**Comment by cx20** [comment]
I confirmed that there is a difference in texture used in `Waterbottle.gltft` and `Waterbottle.glb` using [JglTF](https://github.com/javagl/JglTF/tree/master/jgltf-browser).

Texture used by `Waterbottle.gltf`.
File name : `WaterBottle_occlusionRoughnessMetallic.png`
![image](https://user-images.githubusercontent.com/1833979/42109887-33e66c8a-7c1a-11e8-949c-59b1cf4ecc5d.png)
Texture used by `Waterbottle.glb`
![image](https://user-images.githubusercontent.com/1833979/42109911-46d134a6-7c1a-11e8-9332-551092479c93.png)

It is unknown how it was created, but this texture looks like a composition of several maps (occlusion / roughness / metallic).

**Comment by bghgary** [comment]
> It is unknown how it was created, but this texture looks like a composition of several maps (occlusion / roughness / metallic).

It looks like newer versions of Unity imports this specific PSD incorrectly. Not sure why, but I've switched to using PNGs instead and that fixed it.

**Comment by cx20** [comment]
I tested three modified models with three engines. I think the result is good.

- engines used in the test
  - Three.js r94
  - Babylon.js 3.3.0 alpha
  - Windows 10 version 1803  Explorer preview window

|[glTF](https://github.com/cx20/gltf-test/tree/master/tutorialModels/WaterBottle/glTF) |[glTF-Binary](https://github.com/cx20/gltf-test/tree/master/tutorialModels/WaterBottle/glTF-Binary)|[glTF-pbrSpecularGlossiness](https://github.com/cx20/gltf-test/tree/master/tutorialModels/WaterBottle/glTF-pbrSpecularGlossiness)|
|:---:|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1833979/42121685-88689f7c-7c6e-11e8-8fad-6227585978f1.png)|![image](https://user-images.githubusercontent.com/1833979/42121687-8c046b16-7c6e-11e8-83fc-eac30b839f13.png)|![image](https://user-images.githubusercontent.com/1833979/42121688-90ab50bc-7c6e-11e8-839a-4501e18345d5.png)|
|![image](https://user-images.githubusercontent.com/1833979/42121689-95de282a-7c6e-11e8-96e4-98a26011dd62.png)|![image](https://user-images.githubusercontent.com/1833979/42121691-9ada0b78-7c6e-11e8-8674-acd23a9d8590.png)|![image](https://user-images.githubusercontent.com/1833979/42121692-a1fc8cd2-7c6e-11e8-93b2-e9a6303ceca6.png)|
|![image](https://user-images.githubusercontent.com/1833979/42121693-ab021b1c-7c6e-11e8-90eb-48ed75fd50ea.png)|![image](https://user-images.githubusercontent.com/1833979/42121697-b3cbb302-7c6e-11e8-8bf4-64edcec35588.png)|![image](https://user-images.githubusercontent.com/1833979/42121699-ba3d5826-7c6e-11e8-8b53-9517512a225d.png)|
