### ISSUE TITLE
Sample using COLOR_0 attribute semantic property.

### ISSUE THREAD

**Issue by mseddon** [KhronosGroup/glTF-Sample-Models#182]
Currently there are no samples utilizing the COLOR_0 accessor.

**Comment by bghgary** [comment]
The BoxVertexColor one does.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxVertexColors/glTF/BoxVertexColors.gltf#L112

If you are looking to test specific features, try using the [asset generator tests](https://github.com/bghgary/glTF-Asset-Generator). For vertex colors specifically, look [here](https://github.com/bghgary/glTF-Asset-Generator/blob/master/Output/Mesh_PrimitiveVertexColor)

**Comment by mseddon** [comment]
Ah, I must have missed that one.

I hadn't come across the asset generator, that's a fantastic resource, thanks!
