### ISSUE TITLE
All sample models should include a clear license for usage.

### ISSUE THREAD

**Issue by kkoehne** [KhronosGroup/glTF-Sample-Models#188]
README.md in both 2.0\RiggedFigure, 2.0\RiggedFigure just says

`Donated by [Cesium](http://cesiumjs.org/) for glTF testing.`

about the license. Cesiumjs.org seems to be [available under the Apache License 2.0](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md), but does this also apply for the models?

**Comment by emackey** [comment]
@pjcozzi Could we move these models to CC-BY or something?  Apache 2.0 is a great software license but it's perhaps not the right kind of license for assets.

Maybe we could add a blanket statement to the whole repo, along the lines of "Except where explicitly stated, the models in this repository are available via Creative Commons CC-BY..."

**Comment by pjcozzi** [comment]
> @pjcozzi Could we move these models to CC-BY or something?

Sure, go for it for any models created by AGI.

> Maybe we could add a blanket statement to the whole repo, along the lines of "Except where explicitly stated, the models in this repository are available via Creative Commons CC-BY..."

I don't know about making this so implicit.  If the existing models use CC-BY, I suspect others will follow just like others followed the "Donated by ABC for glTF testing."

**Comment by javagl** [comment]
For me (and probably others, especially some pettifoggers) the meaning of "Donated" is not entirely clear from a license perspective. This could cause some hesitation about whether or how the models may be used. 

From the licenses listed at https://creativecommons.org/licenses/ , I think that https://creativecommons.org/licenses/by/4.0/ would be most suitable, but others may have different preferences. 

In any case, we should make this clear in the top-level README or the README of each asset. (The "Simple Test Models" are in the public domain, each pointing to https://creativecommons.org/publicdomain/zero/1.0/ )

**Comment by emackey** [comment]
Actually I'm going to leave this open until the Microsoft model licenses are applied too.

**Comment by emackey** [comment]
Also, @06wj, can you update your MultiUV test model to include some kind of license?  See #191 for an example.

**Comment by bghgary** [comment]
I've added licenses to all the Microsoft models.

**Comment by emackey** [comment]
@bghgary That's awesome news, thanks!  I will update my two-water-bottle PR soon.

**Comment by emackey** [comment]
I think all sample models have licenses now.  Let me know if I missed any.
