### ISSUE TITLE
Sponza gltf sample has obfuscated texture filenames

### ISSUE THREAD

**Issue by agorgl** [KhronosGroup/glTF-Sample-Models#193]
In the original Sponza PBR Texture pack here: http://www.alexandre-pestana.com/downloads/SponzaPBR_Textures.rar the names are readable but in the converted gltf version here they are not. Can we fix this?

**Comment by ElArtista** [comment]
Spawning original author @Themaister to thread for help!

**Comment by DrX3D** [comment]
It is not clear that Khronos has permission to make a change. If this is still desired, please open a new issue in [glTF-Sample-Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) repo. This issue will be closed by 27 Nov.

**Comment by DrX3D** [comment]
Closed because there are no recent requests
