### ISSUE TITLE
Interpolation Test - Linear Scale is actually Cubic Spline

### ISSUE THREAD

**Issue by leweaver** [KhronosGroup/glTF-Sample-Models#213]
https://github.com/KhronosGroup/glTF-Sample-Models/blob/ec880043ae0cead374d7e3a965cc8323c51b06e1/2.0/InterpolationTest/glTF/InterpolationTest.gltf#L540

It appears that this test model incorrectly uses Cubic Spline interpolation mode for the "Linear Scale" test.

**Comment by cx20** [comment]
@Reon90 Could you confirm it?

**Comment by Reon90** [comment]
yes, I confirm, I have a fixed version.

**Comment by emackey** [comment]
Fixed in #230.
