### ISSUE TITLE
Skin weights do not sum to 1.0

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/glTF-Sample-Models#215]
CesiumMan has many verts whose weights sum to a number less than 1.0, as a result ThreeJS has a hack where it normalizes the weights manually:

https://github.com/mrdoob/three.js/issues/15319

**Comment by donmccurdy** [comment]
Related issue on the validator: https://github.com/KhronosGroup/glTF-Validator/issues/58.

**Comment by donmccurdy** [comment]
Possibly RiggedFigure, too: https://twitter.com/makc3d/status/1114733367231229952

**Comment by emackey** [comment]
Fixed in #245.
