### ISSUE TITLE
pbrSpecularGlossiness BoxInterleaved sample does not contain any extension.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Sample-Models#219]
The model located [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxInterleaved/glTF-pbrSpecularGlossiness) is defined as requiring pbrSpecularGlossiness.

But the actual material does not contain any extension material, it just uses the standard metallic material.

**Comment by bghgary** [comment]
See related #151. I've just opened a PR to remove the bad models.
