### ISSUE TITLE
AntiqueCamera uses different textures for glTF and GLB variants

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Models#222]
All six textures stored in `AntiqueCamera.glb` are 8-bit, while glTF variant has four 16-bit textures.

/cc @UX3D-nopper

**Comment by lexaknyazev** [comment]
Apparently, @emackey has opened a #223 to fix this.

**Comment by emackey** [comment]
Ah, didn't realize someone else had already been assigned.  Hopefully @UX3D-soares had not started work on this yet.

**Comment by UX3D-nopper** [comment]
Actually, if you already solved it, please commit.

**Comment by emackey** [comment]
Yes, I have a PR open with a fix, it's just waiting on the spec issue resolution.

**Comment by emackey** [comment]
The spec issue is still open, but merging #223 fixes the sample model by avoiding 16-bit PNGs.
