### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by mikedh** [KhronosGroup/glTF-Sample-Models#224]
Hi, is there a clear license for the models in this repository? Adding a `LICENSE.md`, even with "each file has all rights reserved by it's contributor" would be great. 

Something MIT/BSD compatible would be awesome, it would be really nice to include some of these files in upstream projects to unit test GLTF/GLB importers in CI.

**Comment by lexaknyazev** [comment]
Each model's readme includes licensing information.

**Comment by donmccurdy** [comment]
Could be handy to include machine-readable SPDX identifiers in `model-index.json`, but yeah the licenses do vary between files.

**Comment by mikedh** [comment]
Gotcha, yeah maybe it would be nice to have a `LICENSE.md` that states each directory has its own license.
