### ISSUE TITLE
improving the texture transform example

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Models#225]
moved from:

https://github.com/KhronosGroup/glTF-Asset-Generator/issues/531

The current texture transform [example](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/TextureTransformTest/glTF/TextureTransformTest.gltf) does not test for anisotropic scale, applied together with a rotation.

An improved, harder test with a scale of 2.0,1.5 and a rotation of 90 degrees:

https://github.com/andreasplesch/gltf-test/blob/textrafo/tutorialModels/TextureTransformTest/glTF/TextureTransformTest.gltf

Indeed, the texture transform reveals disagreement between Three and Babylon:

[Three:](https://raw.githack.com/andreasplesch/gltf-test/841965630a5cd93d2e04cfcc263692dea9190ddb/examples/threejs/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/6171115/58954851-4fff7100-8768-11e9-93cc-5142b727de9d.png)

[Babylon:](https://raw.githack.com/andreasplesch/gltf-test/841965630a5cd93d2e04cfcc263692dea9190ddb/examples/babylonjs/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/6171115/58954904-732a2080-8768-11e9-83f9-3e19313cebb9.png)

Please disregard the green check mark. It is deliberately left in a certainly wrong location.

I think Babylon is correct but I may be misunderstanding the transform construction, see discussion in https://github.com/KhronosGroup/glTF-Asset-Generator/issues/531

Until there is resolution as to what is the correct application, the green check mark could be omitted.

**Comment by andreasplesch** [comment]
oh, #177 is the same issue. Should add a comment there ?

**Comment by bghgary** [comment]
Yeah, I was looking for that issue yesterday and didn't find it. Collapsing these two would be good.

**Comment by andreasplesch** [comment]
closed in favour of #177
