### ISSUE TITLE
Missing license information on many models

### ISSUE THREAD

**Issue by keithroe** [KhronosGroup/glTF-Sample-Models#227]
Many models (eg, 2CylinderEngine) are still missing license info.  This model has this information under the 'license' section:

```
Data conversion from original JT to COLLADA has been kindly performed by Okino Computer Graphics, using Okino Polytrans Software.
```

**Comment by javagl** [comment]
The issue of some models having an unclear license is currently addressed internally. 

For _most_ of the models, the license information has already been sorted out. Some models currently only say "Donated by..." or "Created from...", which is not sufficient. It _might_ be necessary to remove some models, or re-create certain models with a new, known license. There are some (very few) models that may have to use a "mixed license" (e.g. one license for the texture and one for the geometry). 

More generally: There soon will be an update for the license information, and after the update, all models will all have proper, reliable license information (probably in https://spdx.org/licenses/ form, and maybe with some https://reuse.software/ behind that, but I cannot yet make specific promises here).

**Comment by DrX3D** [comment]
All of the models in [Sample Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) have resolved issues. This repo will not be updated with license info. If there are still concerns about licenses, please open an issue in Sample Assets.

This issue will be closed by 27 November.

**Comment by DrX3D** [comment]
Closed because there are no recent requests
