### ISSUE TITLE
Mismatched accessor.count in Monster.gltf/glTF-Draco

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF-Sample-Models#237]
![image](https://user-images.githubusercontent.com/28807867/67839240-25a2bb80-fb2e-11e9-9080-15c8ce90a266.png)

**Comment by shannon** [comment]
@shrinktofit I ran into the same issue in #234 for multiple models. I submitted a PR #236 with patched counts but I think they are going to want to fix this on the exporter.
