### ISSUE TITLE
AlphaBlendModeTest.gltf json has strange "samplers" field in root object.

### ISSUE THREAD

**Issue by psilord** [KhronosGroup/glTF-Sample-Models#241]
Hello,

I find the file `glTF-Sample-Models/2.0/AlphaBlendModeTest/glTF-Embedded/AlphaBlendModeTest.gltf` has this in it:

```
    "samplers" : [
        {}
    ],
```

which I don't think is right. Or at least I don't see that in the spec this is legal.

Thank you.

**Comment by emackey** [comment]
Hi @psilord, this odd snippet of code does pass validation against the [sampler schema](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/sampler.schema.json).  Basically it declares an array of samplers, populated by only a single sampler, which is referenced elsewhere in the file via `"sampler" : 0`.

The values to use in this sampler are all defaults.  For `wrapS` and `wrapT`, the schema provides an explicit default of `10497` which is the enum value for `REPEAT`, so texture coordinates outside the zero-to-one range should repeat the texture image.

For `magFilter` and `minFilter`, the [specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplers) has this to say:

> **Default Filtering Implementation Note:** When filtering options are defined, runtime must use them. Otherwise, it is free to adapt filtering to performance or quality goals.

So for this sampler, implementations are free to choose their preferred texture filtering.

**Comment by psilord** [comment]
Ah I see. This all makes sense now. Thank you!
