### ISSUE TITLE
Some models use data-uri media type 'gltf-buffer' instead of 'octet-stream', is it right?

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF-Sample-Models#244]
[spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#file-extensions-and-mime-types) says:
> *.bin files use application/octet-stream

So I add this validation to my glTF reader. Is this necessary or should I just ignore the media type when decode buffer data-uri?

**Comment by lexaknyazev** [comment]
There's a pending PR to update the spec: https://github.com/KhronosGroup/glTF/pull/1180

Both options are valid.
