### ISSUE TITLE
Sample of KHR_mesh_quantization needed

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Models#246]
@zeux I don't suppose you have a public asset that you could contribute?

**Comment by zeux** [comment]
This is easy :) I can take any model from glTF-Sample-Models and convert it. Any preferences? We could do this the same way Draco does and add glTF-Quantized folders or smth like that to a few sample models.

**Comment by emackey** [comment]
Yeah, maybe just a few to start with.  `Avocado` and `Lantern` might be good starting points.

**Comment by emackey** [comment]
Thanks!

**Comment by cx20** [comment]
I tried adding these models to [gltf-test](https://github.com/cx20/gltf-test#format-tests).
At present, only four libraries support the `KHR_mesh_quantization` extension in the observation range.
![image](https://user-images.githubusercontent.com/1833979/72737785-9c0e0180-3be3-11ea-9010-e9fcdf22d57e.png)

**Comment by cx20** [comment]
I'm sorry. The format comparison table in [gltf-test](https://github.com/cx20/gltf-test#format-tests) for the other day was incorrect. `Avocado/glTF-Embedded` did not actually exist.
I think it would be helpful to have `Duck` model so we can compare several formats.

**Comment by zeux** [comment]
One duck coming right up.

[Duck-Quantized.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/4101204/Duck-Quantized.zip)

**Comment by cx20** [comment]
@zeux Thank you for providing the sample model. I tried adding Duck's `glTF-Quantized` format to [gltf-test](https://github.com/cx20/gltf-test#format-tests).

![image](https://user-images.githubusercontent.com/1833979/72989873-76c30280-3e32-11ea-9bd5-37c082ec7f2e.png)

BTW, pex-renderer also supported this format. At this time, there are five libraries that support this format.
