### ISSUE TITLE
Hololens issues with FlightHelmet.gltf

### ISSUE THREAD

**Issue by edgarrodrigosantos** [KhronosGroup/glTF-Sample-Models#252]
We created a very simple demo for Hololens that loads the FlightHelmet.gltf from here:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet/glTF

Everytime we start the app, different (almost random) components appear without texture / with strange artifacts / weird materials.

Is there something we can do? 
Also, what is the best version of the code to use? I'm asking because there hasn't been a release for some time and last time I pulled the master branch, it didn't compile on Unity 2019.2 (now 2019.3).

Thanks

**Comment by donmccurdy** [comment]
>  Also, what is the best version of the code to use? I'm asking because there hasn't been a release for some time and last time I pulled the master branch, it didn't compile on Unity 2019.2 (now 2019.3).

Which code do you mean? There's none in this repo, I'm afraid I don't know much about Hololens.

**Comment by bghgary** [comment]
@edgarrodrigosantos Did you mean to post this to the UnityGLTF repo?

**Comment by edgarrodrigosantos** [comment]
I'm sorry, I did mean to post this on the UnityGLTF repo.
