### ISSUE TITLE
Animated cube example rotating opposite direction?

### ISSUE THREAD

**Issue by Leadwerks** [KhronosGroup/glTF-Sample-Models#253]
Both Windows 3D Viewer and my own code I just implemented show the cube rotating clockwise, but the GIF shows it going the other way.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedCube

I suggest fixing or removing the image, if it is in fact incorrect, because developers are likely to use this model as their first test for animation.

**Comment by bghgary** [comment]
The GIF does indeed look like it's rotating the wrong direction. @UX3D-nopper, I believe you added this asset? Can you confirm?

If you are testing your client implementation, I would suggest also using [glTF-Asset-Generator](https://github.com/KhronosGroup/glTF-Asset-Generator) for testing.

See [Animation_Node](https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Animation_Node) and [Animation_NodeMisc](https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Animation_NodeMisc) for node animations.

**Comment by UX3D-nopper** [comment]
Yes, I added this asset during the specifaction of glTF 2.0. The animated glTF cube is rotating clockwise. The animated GIF is wrong.

**Comment by Leadwerks** [comment]
Here's a quick fix:

![screenshot](https://user-images.githubusercontent.com/108503/74244121-9fc80c00-4ce9-11ea-8aea-eb29f91305e3.gif)

**Comment by UX3D-nopper** [comment]
Suggest u do a pull request.

**Comment by emackey** [comment]
Fixed in d7d0bd16684c1393a.
