### ISSUE TITLE
computevertexnormal, issue

### ISSUE THREAD

**Issue by ashishsiddharth** [KhronosGroup/glTF-Sample-Models#256]
Hi, What is wrong in here?? why isn't it working?

If i am using stl file format, it is working fine. but when i am trying to use glb there is an error with computevertexnormal. 

```
const threeGlasses = new THREE.Object3D();
const loader = new THREE.GLTFLoader();
   loader.load( 'models3D/glasses.glb', function (glassesFramesGeometry) {
		glassesFramesGeometry.computeVertexNormals();
		const glassesFramesMesh = new THREE.Mesh(glassesFramesGeometry);
		threeGlasses.add(glassesFramesMesh.scene)		
   });

  const occluderMesh = THREE.JeelizHelper.create_threejsOccluder(spec.occluderURL);
  
  return {
    glasses: threeGlasses,
    occluder: occluderMesh
  };
```

**Comment by donmccurdy** [comment]
This repository is a collection of sample glTF models. For help with three.js, please use the three.js forums: https://discourse.threejs.org/. You may also want to refer to the [three.js GLTFLoader docs](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) — the result of the load callback is not a geometry, like perhaps STLLoader returns, it is a `Group` that must be traversed to find mesh(es) and their geometries.
