### ISSUE TITLE
how to compress bin file to draco format bin

### ISSUE THREAD

**Issue by jakkypan** [KhronosGroup/glTF-Sample-Models#257]
i want to compress the .bin file, but i cannot find any tool to compress it, how did you achieve that?

**Comment by donmccurdy** [comment]
The most common tool for this is [glTF-Pipeline](https://github.com/CesiumGS/gltf-pipeline). For example:

```shell
# input
model.gltf
model.bin

$ gltf-pipeline -i model.gltf -o model_compressed.glb -d -b

# output
model_compressed.glb
```

**Comment by donmccurdy** [comment]
Recent versions of Blender also have Draco as an export option.

**Comment by jakkypan** [comment]
![image](https://user-images.githubusercontent.com/15864446/77032825-7c773780-69e0-11ea-8e64-118d9287e3e8.png)

as you mentioned, i have try using the common tool, but it did not output anything and it went wrong, why??

by the way, how to use Blender to export Draco compression glb? from which version of blender?

**Comment by donmccurdy** [comment]
It sounds like your version of node.js may be outdated. If updating it does not help, I'd suggest filing an issue on the glTF-Pipeline repository.

> by the way, how to use Blender to export Draco compression glb? from which version of blender?

2.80+, if I remember right.
