### ISSUE TITLE
Some of the models were updated and the Draco versions removed

### ISSUE THREAD

**Issue by FrankGalligan** [KhronosGroup/glTF-Sample-Models#258]
It looks like the Draco versions were removed from:
CesiumMan
CesiumMilkTruck
RiggedFigure

I'm not sure of the protocol for removing models or specific versions of models. But if developers were using these models for implementation/testing then removing them might not be the best solution.

Maybe there should be a list of people (owners) for certain types of models or specific models that need to review PRs? Or in case of extensions the models could be removed and the owners could be notified to update the models.

**Comment by emackey** [comment]
Hi Frank, the models in question were redone, and I don't seem to have a means to create the updated Draco versions.  If there's some way to create new Draco versions, based on the newly updated glTF models and not the old COLLADA models, I'd welcome a PR to bring them into this repo.
