### ISSUE TITLE
CI to validate models

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#26]
It would be super cool to setup CI that
* Runs @lexaknyazev's [glTF Validator](https://github.com/KhronosGroup/glTF-Validator) on new/updated models in a PR
* Use popular WebGL engines to preview them like @cx20's [gltf-test](https://github.com/cx20/gltf-test).  This could be great to find issues in the models and engines.
* Generate website to browse samples, #77

Contributions here are very welcome!

**Comment by lexaknyazev** [comment]
I've opened a meta-issue in Validator repo to track this. Will do integration stuff from Validator's side.

**Comment by kyasbal-1994** [comment]
And if there was zip task to compress each models to download easily, it is great.
I don't want to download whole zip or clone all models when I just want to test a model file.

**Comment by donmccurdy** [comment]
@kyasbal-1994 it would be nice to have something more obvious/discoverable, but you can download individual directories using this tool: http://kinolien.github.io/gitzip/

**Comment by lexaknyazev** [comment]
@Khronoswebmaster 
Could you enable Travis for this repo?

**Comment by outofcontrol** [comment]
Enabled. Do you need Appveyor as well?

**Comment by lexaknyazev** [comment]
Just enabled CI validation for 2.0 models.

**Comment by pjcozzi** [comment]
> Do you need Appveyor as well?

Not for this repo.

**Comment by emackey** [comment]
Has this CI already run on the master branch?  Is there a link to the results?

**Comment by lexaknyazev** [comment]
It runs on making a commit or opening PR to `master`. 

Some models contain errors, so CI build is failing. 

https://travis-ci.org/KhronosGroup/glTF-Sample-Models

We should add a badge with status to repo's readme.

**Comment by lexaknyazev** [comment]
Badge added.

**Comment by pjcozzi** [comment]
> Use popular WebGL engines to preview them like @cx20's gltf-test. This could be great to find issues in the models and engines.

See https://github.com/KhronosGroup/glTF/issues/1081#issuecomment-343701907

**Comment by emackey** [comment]
This was added some time ago.  The results are visible in the GitHub Actions tab.
