### ISSUE TITLE
There are two models in the Draco format folder of MorphPrimitivesTest

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/glTF-Sample-Models#260]
There are two models `MorphPrimitivesTest.glb` and `MorphPrimitivesTest.gltf` in the following folders.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphPrimitivesTest/glTF-Draco

Currently, `model-index.json` refers to `.glb` as a `Draco` format model, but I think that it is necessary to change the reference destination because `.gltf` is newer.

**Comment by emackey** [comment]
Good catch, thanks @cx20.

**Comment by cx20** [comment]
Thanks!
