### ISSUE TITLE
EnvironmentTest and TransmissionTest accessor min/max type bug

### ISSUE THREAD

**Issue by Loftilus** [KhronosGroup/glTF-Sample-Models#276]
Some accessors in EnvironmentTest and TransmissionTest has componentType 5125 (Unsigned int) but the min and max values are specified with double.

From the glTF spec:

> accessor.min and accessor.max properties are arrays that contain per-component minimum and maximum values, respectively. Exporters and loaders must treat these values as having the same data type as accessor's componentType, i.e., use integers (JSON number without fractional part) for integer types and use floating-point decimals for 5126 (FLOAT).

**Comment by MiiBond** [comment]
@Loftilus thanks for pointing that out. That's a bug in the Adobe Dimension exporter and it has been filed.
