### ISSUE TITLE
Import Polly model from the blender repository.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Sample-Models#298]
As discussed [here](https://github.com/KhronosGroup/glTF-Blender-IO/issues/371#issuecomment-783924919), it could be interesting to import the Polly model from the blender repository to this repository.

Polly model is a good test case that combines many glTF features into a single file.

It is good to have test cases that test individual features, but in my experience, some of these features fall down when tested in combination with other features, so I would like to see more "feature complete" models here.

**Comment by cx20** [comment]
I agree that the Polly model is a valid model for testing many of the features of glTF 2.0.
I'm a little concerned about the size of this repository, but if it's just a `.glb` format file (about 40MB), it should be fine.

**Comment by donmccurdy** [comment]
Copying over from https://github.com/KhronosGroup/glTF-Blender-IO/issues/371#issuecomment-783924919, my understanding is that the .blend will need some changes, to use the Principled BSDF material rather than the old custom nodes. In the past there were some problems supporting it, but it looks like re-importing the original .glb and then exporting from Blender works correctly, so maybe all of those issues have been fixed...

**Comment by vpenades** [comment]
@donmccurdy It is a requiremnt to provide the model source to add a model to this repository? I was thinking on contributing a model, but it's been generated programatically, so it would not have a model source...

**Comment by donmccurdy** [comment]
Not a requirement, as far as I know. I think we'd prefer to have it where one exists though, e.g. to provide the original textures and animation keyframes that might have been resampled.

**Comment by cx20** [comment]
I don't think I need to place the Blender source for this model for now either. This is because I'm worried about the size of the repository getting bloated.

Or maybe it would be better to have a separate repository for the model source.

I will link to the following issue as a related topic.
https://github.com/KhronosGroup/glTF-Sample-Models/issues/272

**Comment by cx20** [comment]
BTW, my personal hope is that Polly's nameplate will be improved.

https://github.com/KhronosGroup/glTF-Blender-IO/issues/1264
![image](https://user-images.githubusercontent.com/1833979/109173810-995ae400-77c7-11eb-86d5-7a6f06c04f78.png)

**Comment by donmccurdy** [comment]
Let's keep the source and glTF models together if we can — we have other options for dealing with the size of the repo, like Git LFS, if needed. I don't think that separating them will do much about overall size in the long term.

There are a few issues in the `.blend` that should probably be fixed though, yes. I'd forgotten the thread in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1264.

**Comment by vpenades** [comment]
@donmccurdy if repository size is a concern, maybe I would split it into 1.0 and 2.0 files.... or maybe I would remove 1.0 directory altogether? I'm not sure if anyone is actually using glTF 1.0 files anymore....

**Comment by cx20** [comment]
@donmccurdy 

> Let's keep the source and glTF models together if we can

Yes, it is. I agree that things will be simpler if the model sources are also included in the same repository.

> There are a few issues in the .blend that should probably be fixed though, yes.

Yes, it is. If we are going to include the `.blend` file, it is preferable that the issue be fixed.

@vpenades 

> if repository size is a concern, maybe I would split it into 1.0 and 2.0 files.

Personally, I think it would be better to make glTF 1.0 a separate branch.

**Comment by donmccurdy** [comment]
@emackey has been investigating options for dealing with repository size — I don't think we need to solve it here, let's start a new issue for considering alternatives. I think the only real obstacle to including Polly in this repository is getting it updated to be compatible with more recent versions of Blender.

**Comment by DrX3D** [comment]
The request (PR) to add new models needs to be made by someone with knowledge of the model that can create the necessary supporting files (README, license, etc.). Please create a PR in [Sample Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) repo. 

If there is no response to this comment by 27 Nov, then this issue will be closed.

**Comment by DrX3D** [comment]
Closed because there are no recent requests
