### ISSUE TITLE
Clearcoat Test model is wrong

### ISSUE THREAD

**Issue by frguthmann** [KhronosGroup/glTF-Sample-Models#304]
The coating only part of "Roughness Variations" doesn't have any clearcoat. The roughness variation is attached to the base layer. This is not what this model is supposed to display. I would correct it but I'm not sure what software to use. I made one with the BabylonJS sandbox but it doesn't export correctly.

**Comment by cx20** [comment]
Hi @frguthmann 
I tried to re-export [ClearCloadTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ClearCoatTest) with [BabylonJS sandbox](https://sandbox.babylonjs.com/).
As you say, the BabylonJS sandbox export result does not seem to support the output of some materials.

|ClearCloadTest.gltf|BabylonJS sandbox re-exported|
|:----------:|:----------:|
|![image](https://user-images.githubusercontent.com/1833979/111853609-13156600-895f-11eb-82e2-9638b2d5bdbc.png)|![image](https://user-images.githubusercontent.com/1833979/111853654-448e3180-895f-11eb-86a8-ec6bdb2bab43.png)|

The source for this test model is made in `Blender`. You can find the `.blend` file below and try to display it in Blender.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/ClearCoatTest

**Comment by frguthmann** [comment]
Hi, 

Thanks for the input on the original model. On closer inspection I guess it's meant to be that way? It was pretty confusing to me that 'coating only' column does not mean you're looking at the coating layer itself. From what I see, it's a base layer that has the same properties as the clearcoat layer of the coated column.

It's all good, sorry about that!
