### ISSUE TITLE
unrecognized file extension ""

### ISSUE THREAD

**Issue by alinaiim** [KhronosGroup/glTF-Sample-Models#308]
I have a glb file that I'm trying to apply draco compression to. When the file is on the desktop the compression works perfectly.
But I have a resources folder on the machine and when I type the same command it gives an error
***unrecognized file extension ""***
Which is weird because I am not changing the files(or the extensions) on the resources directory.

I don't know if this is a windows error or an issue with gltf pipeline command

**Comment by javagl** [comment]
I assume this an issue for https://github.com/CesiumGS/gltf-pipeline , right?
