### ISSUE TITLE
Open source lib to convert 3d model to GLTF on server side

### ISSUE THREAD

**Issue by PritishSawant** [KhronosGroup/glTF-Sample-Models#311]
I am trying to convert 3d models to gltf using server side tech so that i can display in unity as Asset bundle requires manual conversion which is not appropriate for my project. Currently i am using Nodejs and using this lib  CesiumGS/obj2gltf: Convert OBJ assets to glTF (github.com)  but it only supports obj format. Does any know other open source lib which are well maintained. I am ok for other server side tech as well.

**Comment by donmccurdy** [comment]
The http://github.khronos.org/glTF-Project-Explorer/ listing is probably the place to find this information. In general, supporting conversion to/from every possible combination of formats is an extremely complicated problem, and tools that focus on a single specific conversion (e.g. FBX to glTF) generally work better. But my impression is that Assimp (https://github.com/assimp/assimp) is the most popular general-purpose converter.

**Comment by PritishSawant** [comment]
@donmccurdy Thanks
