### ISSUE TITLE
Normal textures as linear or sRGB colorspace?

### ISSUE THREAD

**Issue by JulianVallee** [KhronosGroup/glTF-Sample-Models#316]
The [glTF 2.0 specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialnormaltexture) defines normal textures to be in linear colorspace, but it appears that (at least) the following models have their normal textures in sRGB colorspace:

 - [NormalTangentTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest)
 - [NormalTangentMirrorTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentMirrorTest)
 - [Sponza](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza)

This caused some issues with my OpenGL normal mapping, as ImageMagick detects the normal textures to be in sRGB colorspace which subsequently messes up the TBN matrix.

I have also used the ImageMagick command line tool identify and Gimp, which both say that the textures are in sRGB colorspace. 

As a workaround I can either overwrite the normal texture files colorspace to RGB, this way ImageMagick detects it properly and my engine uploads it with the correct pixel format. Or I can ignore the colorspace for normal textures and always use a linear pixel format. Both seem to work and result in proper normals/reflections.

I'm a bit unsure about my observations though, as I have found absolutely no information about this exact issue using google.

Colors of the normals are a little bit off due to HDR rendering, but it should show the problem nonetheless:
![normal_colorspace](https://user-images.githubusercontent.com/6720458/121833902-b0b5d280-cccd-11eb-8083-d9756c5f1c80.png)

**Comment by donmccurdy** [comment]
From the glTF spec's [Images section](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#images) —

> Any colorspace information (such as ICC profiles, intents, etc) from PNG or JPEG containers must be ignored. Effective transfer function is defined by a glTF object that refers to the image.
>
> > **Implementation Note:** This increases portability of an asset, since not all image decoding libraries fully support custom color conversions. To achieve correct rendering, WebGL runtimes must disable such conversions by setting UNPACK_COLORSPACE_CONVERSION_WEBGL flag to NONE.

Ideally, normal textures from the official samples would have correct metadata, even if that information is meant to be ignored... but practically, these models are coming from many different sources and that's a bit difficult to detect and enforce. We can file bugs on the authoring tools, perhaps? These examples were created by:

- COLLADA2GLTF
- Blender
- Granite (https://github.com/Themaister/Granite)

**Comment by JulianVallee** [comment]
That was a fast answer, thank you so much! 

Your link was exactly what I was missing, explains what I have observed pretty well. Looks like I'm on the right track by treating normals as linear textures then.

Regarding the meta data, I have read the relevant specification parts again and think that adding meta data for the normal texture colorprofiles would be kind of redundant. The [images section](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#images) doesn't mention normal textures explicitly, while the actual [normal texture section](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialnormaltexture) defines normals to be in linear space. 

Given that, we should be safe by always interpreting JPEG and PNG normal textures as linear data, without any additional meta data or colorspace information?

**Comment by lexaknyazev** [comment]
> Given that, we should be safe by always interpreting JPEG and PNG normal textures as linear data, without any additional meta data or colorspace information?

Yes. Keep in mind that other non-color textures (occlusion, roughness, etc) also contain linear data.

**Comment by jeannekamikaze** [comment]
Late to the party, but how should an implementation tell what colour space to use for a texture? For example, the [DamagedHelmet sample](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf) only has one sampler, and it is empty. So when an implementation loads a texture, what clue does it have that the texture is a normal map?

**Comment by donmccurdy** [comment]
@jeannekamikaze it would be necessary to parse a material definition referencing the texture, and then identify the color space of the texture based on its role. In loaders I've written, I'll begin downloading the texture immediately, but wait to upload to the GPU until the texture is associated with a material. Typically the color space is not needed until GPU upload.

While you can do sRGB→Linear conversion in shader code, there are [subtle problems](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureLinearInterpolationTest) with that approach. I would expect that whatever graphics API you're using should have some way to do this for you when sampling — here's a [summary for OpenGL](https://stackoverflow.com/a/10348719/1314762).

**Comment by jeannekamikaze** [comment]
@donmccurdy thank you, that style of lazy loading is what I ended up implementing, deferring the GPU upload until I know what the texture is used for.

I'll check out that sample you linked, I was not aware of functional differences between the two approaches. The shader code conversion I think is also more expensive, especially since we may end up sampling a handful of textures.

**Comment by helviett** [comment]
In my opinion such *subtleties* make glTF unusable for real engines that want to use it as scene format. For me it's obvious that it's much *better* and more *performant* to determine image format from the content (actual texture located on a disk) rather than indirectly using material properties.

**Comment by donmccurdy** [comment]
Two complicating factors:

1. producing (for example) normal maps with the wrong ICC profile is incredibly easy to do
2. some environments (particularly WebGL) cannot access the ICC profile to check it

Workarounds exist for WebGL, but, they're worse.

For that reason I do feel that glTF is correct to mandate what the color space of each image must be, based on its role on the material.  No one wants sRGB-encoded normal maps. But also, it would be nice for the ICC profiles to be correct, that is a tougher problem ecosystem-wide. Having tools to detect the issue (glTF-Validator?) and to fix it (glTF-Transform?) might be a good step.
