### ISSUE TITLE
everyone can edit files freely

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [KhronosGroup/glTF-Sample-Models#317]
i'm only including this as an issue because that means someone can delete the directory or upload malicious files

**Comment by donmccurdy** [comment]
Sorry, could you clarify what you mean here? Anyone can submit a PR but such changes are reviewed by the team before merging, as is standard for Git repositories.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
i just have an option to upload files directly to here from github

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
when i made that issue, it just straight up gave me the option to delete the directory
for some reason there's an upload button here too (there isn't on other reposotories) but it says i don't have upload permissions

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
but i can still create files

**Comment by donmccurdy** [comment]
Clicking a "delete directory" button will take you to a page similar to this:

![Screen Shot 2021-06-17 at 2 28 47 PM](https://user-images.githubusercontent.com/1848368/122474711-758afc00-cf78-11eb-9435-809679c6daf8.png)

Such proposals can be made on any repository on GitHub, but fortunately they are subject to maintainer review. 🙂
