### ISSUE TITLE
Add MosquitoInAmber.glb and PearlGoldOliveCoveredGlassDish glb to samples

### ISSUE THREAD

**Issue by wallabyway** [KhronosGroup/glTF-Sample-Models#318]
Placeholder for me (and/or  Ed M. for Mosquito.glb & Alex for glassDish.glb )  to add these gib's to the sample repo.
These assets are still being tweaked, before being published.
![reversed](https://user-images.githubusercontent.com/440241/124004373-c8a77a80-d98c-11eb-963a-208ef70a6d6d.gif)
![glass-dish-ollives](https://user-images.githubusercontent.com/440241/124004585-03a9ae00-d98d-11eb-9e0d-d4b59e6f9df3.jpg)

**Comment by echadwick-wayfair** [comment]
Talking offline, it was decided these will be submitted individually by the authors of the assets, and they'll be added as Pull Requests rather than as Issues.

**Comment by echadwick-wayfair** [comment]
The glass dish is here: https://github.com/KhronosGroup/glTF-Sample-Models/pull/319

I still have some work to do on the asset, hopefully finishing it today.

**Comment by wallabyway** [comment]
The press-release is published here: 
https://www.khronos.org/news/press/new-gltf-extensions-raise-the-bar-on-3d-asset-visual-realism

It all looks good.   The PearlGoldOliveCoveredGlassDish.gltf is added to the samples repo (Thanks @echadwick-wayfair ) and the press-release correctly points to it.

However, the mosquitoInAmber.gltf used in the press-release is still pointing to a personal copy of the gltf file.

@emackey - I think you are the custodian of the mosquitoInAmber.gltf..   do you mind if I add this mosquitoInAmber.gltf file to the samples repo, and then update the press-release to point to this samples repo version ?

**Comment by emackey** [comment]
@wallabyway If you're able to open a Pull Request here for the mosquito, that would be helpful, thanks.

**Comment by wallabyway** [comment]
ok... finally got around to doing this... 

Here's the pull request:
https://github.com/KhronosGroup/glTF-Sample-Models/pull/328

**Comment by emackey** [comment]
Done.
