### ISSUE TITLE
RecursiveSkeletons is not a valid glTF file

### ISSUE THREAD

**Issue by kovacsv** [KhronosGroup/glTF-Sample-Models#337]
Maybe I missed something, but the RecursiveSkeletons file seems to have invalid vertex colors.

According to the specification, _"All components of each COLOR_0 accessor element MUST be clamped to [0.0, 1.0] range."_, but in the RecursiveSkeletons model all vertex colors are `[255, 255, 255, 255]`.

**Comment by lexaknyazev** [comment]
The accessor referred by the `COLOR_0` attribute has _normalized unsigned byte_ component type. This means that effective color values are `[1.0, 1.0, 1.0, 1.0]`.

**Comment by kovacsv** [comment]
By bad, I misunderstood the specification. Thanks for the clarification.
