### ISSUE TITLE
bufferView#target of BoomBox sample

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/glTF-Sample-Models#34]
Is this valid data?

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoomBox/glTF/BoomBox.gltf#L93

I think this bufferView.target should be WebGLRenderingContext.ELEMENT_ARRAY_BUFFER not ARRAY_BUFFER.

**Comment by bghgary** [comment]
Thanks for the report. I will fix this.

**Comment by pjcozzi** [comment]
@kyasbal-1994 thanks again for the report.  @bghgary fixed this in #35.
