### ISSUE TITLE
Blender GLTF fails the gLTF validation

### ISSUE THREAD

**Issue by suparthghimire** [KhronosGroup/glTF-Sample-Models#358]
I exported a .blend file to gltf format (seperate). The file when tested in .gLTF validator, generates several issues (discard the Resource Not Found Error). What thing am I doing wrong?

**Comment by donmccurdy** [comment]
Hi @suparthghimire — these repository is a collection of sample models, not really related to the Blender exporter or the glTF validator. I think the best place to get help with this question would be one of these sites, in order of recommendation:

1. https://blender.stackexchange.com/
2. https://github.com/KhronosGroup/glTF-Blender-IO
3. https://github.com/KhronosGroup/glTF-Validator/

**Comment by javagl** [comment]
^this. But if you open an issue in either of the repositories, I'd recommend to include more information about the validation errors, or even better, provide the model itself, if possible. Without this information, it's nearly impossible to provide a (technical) answer here....
