### ISSUE TITLE
Node mesh declaration doesn't seem compliant with the spec

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF-Sample-Models#36]
Hi, 

First of all, thanks a lot for these samples, they are very helpful.
When testing the BoomBox sample, I had an issue and saw that the mesh data in the node seems not compliant with the spec:

The [samples](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoomBox/glTF/BoomBox.gltf#L166) has `"mesh": 0,` but the [spec seems to expect](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/examples/nodes.json#L6-L8) this `"meshes": [0],`

Did I miss something or is it an actual small issue?

Thanks!

**Comment by lexaknyazev** [comment]
Examples haven't been updated yet. Please refer to Schemas:

https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/node.schema.json

**Comment by AurL** [comment]
Ok thanks a lot

**Comment by bghgary** [comment]
The boom box example should be up to date. Let me know if it isn't. The mesh being just an index now is a change in 2.0.

**Comment by AurL** [comment]
Yes. It seems that I was following an older version of the specification, 
Sorry for that.
