### ISSUE TITLE
Missing license for VertexColorTest

### ISSUE THREAD

**Issue by aidinabedi** [KhronosGroup/glTF-Sample-Models#370]
What's the license information for [VertexColorTest](/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VertexColorTest)?

**Comment by javagl** [comment]
To avoid having too many issues open, I'll close this one as duplicate of https://github.com/KhronosGroup/glTF-Sample-Models/issues/227 (and leave a comment there)
