### ISSUE TITLE
Missing license for BoxVertexColors

### ISSUE THREAD

**Issue by aidinabedi** [KhronosGroup/glTF-Sample-Models#371]
What's the actual license for [BoxVertexColors](/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxVertexColors)? Public domain? CC BY 4.0?

**Comment by javagl** [comment]
To avoid having too many issues open, I'll close this one as duplicate of https://github.com/KhronosGroup/glTF-Sample-Models/issues/227 (and leave a comment there)
