### ISSUE TITLE
Many models missing AO channel

### ISSUE THREAD

**Issue by elalish** [KhronosGroup/glTF-Sample-Models#372]
Some examples: https://modelviewer.dev/fidelity/#khronos-SheenCloth, https://modelviewer.dev/fidelity/#khronos-2CylinderEngine, https://modelviewer.dev/fidelity/#khronos-BrainStem

When comparing to path-traced renderers, which we should always be doing, it's not really a fair comparison if the model hasn't had its AO channel properly baked, as this extra data is required to help rasterizers achieve realistic results. This is a common enough problem in the glTF ecosystem - we should not encourage the idea that it's somehow optional for PBR models.

**Comment by DrX3D** [comment]
This issue really only applies to SheenCloth as 2CylinderEngine is not in the new repo and BrainStem was converted and is not up to the usual license standards. 

@elalish : Can this topic be opened as an issue on [Sample Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) for just SheenCloth?

If there is no response to this comment by 27 Nov, then this issue will be closed.

**Comment by bghgary** [comment]
@elalish I'm not sure why you say SheenCloth doesn't have AO. It's in the [glTF JSON](https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/SheenCloth/glTF/SheenCloth.gltf#L163-L173) and the map looks like this:
![image](https://github.com/KhronosGroup/glTF-Sample-Models/assets/19158740/7878303d-1b2f-4d28-afe3-76c3e0e0b13d)

**Comment by donmccurdy** [comment]
> AO is for geometry-level occlusion, so the dark parts in the folds.

I'd have to disagree with this — there's no reason you can't or shouldn't bake AO with greater detail than your geometry. Similar to how we bake small concavities into normal maps and remove them from geometry.

Agreed with @elalish that baking AO without tiling would improve the visual result for SheenCloth.glb, though. Especially in a PBR showcase model, that's worth doing. For 2CylinderEngine.glb and BrainStem.glb, I have mixed feelings, one is animated and the other looks strongly as if it is meant to be animated or disassembled, for which baked AO would probably be the wrong approach, compared to SSAO or other techniques.

**Comment by DrX3D** [comment]
@elalish , @donmccurdy : Would it be sufficient to handle on SheenCloth as there are issues with the other two models?

This needs to be commented on with intended resolution by 1 Dec or it will be closed.

**Comment by elalish** [comment]
Yes, that works for me. Who contributed the original? Any chance their modeling program can bake out AO and re-export?

**Comment by bghgary** [comment]
@PatrickRyanMS Can you comment on the SheenCloth AO?

**Comment by PatrickRyanMS** [comment]
Here's the update https://github.com/KhronosGroup/glTF-Sample-Assets/pull/81
