### ISSUE TITLE
stainedGlassLamp/glTF-JPG-PNG alpha is 0.5

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Sample-Models#377]
The no extension JPG-PNG variant of the stained glass lamp model has a base color alpha for the amber beads of 0.5:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/StainedGlassLamp/glTF-JPG-PNG/StainedGlassLamp.gltf#L581

while it should have an alpha of 0.75 according to the description at

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/StainedGlassLamp#gltf-jpg-png

which also looks better.

So either the material or the description should be updated.

**Comment by bghgary** [comment]
@echadwick-wayfair?

**Comment by andreasplesch** [comment]
I only noticed because of two conspiring bugs in my renderer which completely clipped the amber beads due to incorrect alphacutoff interpretation. Probably nobody had really noticed before but the beads do look better with higher opacity.

**Comment by echadwick-wayfair** [comment]
Thanks for the catch! Also fixed some missing bufferViews.

**Comment by andreasplesch** [comment]
Thanks. Here is the result for me:
![image](https://user-images.githubusercontent.com/6171115/221047870-5eba8ec7-cf48-445f-923b-6c42f2cab206.png)
