### ISSUE TITLE
🔥🔥🔥convert obj 3d model to gltf model on server side

### ISSUE THREAD

**Issue by yfq512** [KhronosGroup/glTF-Sample-Models#381]
I have three files(test.jpg, test.mtl, test.obj), How can I convert them to a gltf file on server side?
![03083](https://user-images.githubusercontent.com/52442277/223648741-c967062f-885c-4091-8fa1-17bf9c0c0a64.png)

**Comment by bghgary** [comment]
This repo is for sample models. [The glTF forum](https://community.khronos.org/c/gltf-general/45) would be a better place for this question.

One option is to use [obj2gltf](https://github.com/CesiumGS/obj2gltf) to do the conversion. Please ask this question on the forum if you need further discussions.
