### ISSUE TITLE
Iridescence test model?

### ISSUE THREAD

**Issue by bhouston** [KhronosGroup/glTF-Sample-Models#392]
I notice that the current iridescence feature is implemented inconsistently in a lot of renderers.  Basically the colors differ in each renderer.  I wonder if that is in part because we do not have clear test files for iridescence.

Basically a test that isolates iridescence and looks at it across its parameter space so that people can easily validate their implementations.

It may be nice to have a test file for iridescence that has different thickness (min, max) in a row each on say a block with a varying thickness texture.  Then people can compare the behavior under different conditions to ensure proper behavior.

cc: @echadwick-artist

**Comment by bhouston** [comment]
We noticed this as we are adding Blender Cycles and Chaos V-Ray to @elalish's Model Viewer fidelity test suite: 
* https://github.com/google/model-viewer/issues/4482
* https://github.com/google/model-viewer/issues/4483

**Comment by echadwick-artist** [comment]
We have some test models in the new glTF Sample Assets repo, which is meant to replace glTF Sample Models (once we get the kinks worked out).
- [IridescenceMetallicSpheres](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescenceMetallicSpheres#iridescence-metallic-spheres) has a 3d grid of spheres representing the combinations of three settings: iridescenceThickness, baseColorFactor, and iridescenceIor. 
- [IridescenceSuzanne](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescenceSuzanne#iridescence-suzanne) has an iridescenceThicknessTexture, but it's not representing specific values. 

I guess we could add a unit test example that uses a texture to represent specific iridescence thicknesses.

**Comment by bhouston** [comment]
Amazing as usual @echadwick-artist !  Duplicate repos are confusing. :)

**Comment by DrX3D** [comment]
@bhouston : Is this issue complete with these models in the repo?

- Anisotropy: https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/AnisotropyBarnLamp/README.md
- Iridescence: https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/IridescenceAbalone/README.md

There are others too.

**Comment by DrX3D** [comment]
If there are no responses to this comment by 27 Nov, it will be closed.

**Comment by DrX3D** [comment]
No responses by cutoff date - closing.
