### ISSUE TITLE
Anisotropy test model?

### ISSUE THREAD

**Issue by bhouston** [KhronosGroup/glTF-Sample-Models#393]
I notice that we are missing any anisotropy models/examples.  I think it would be useful to have a test model that shows off anisotropy in a few different scenarios.

The two main use cases for anisotropy are basically:
1. A circular anisotropy, like on the bottom of a pot
2. A carbon fibber weave anisotropy, everyone loves this.

Then I think there are a few complications that we could demonstrate to ensure people implement it correctly:
3. The above scenarios where the anisotropy texture is rotated via the texture extension (does the anisotropy rotate or not? should it?)
5. The above with an additional normal map on it.
6. The above with a clear coat on top.

cc: @echadwick-artist

**Comment by bhouston** [comment]
We noticed this as we are adding Blender Cycles and Chaos V-Ray to @elalish's Model Viewer fidelity test suite: 
* https://github.com/google/model-viewer/issues/4482
* https://github.com/google/model-viewer/issues/4483

**Comment by echadwick-artist** [comment]
Thanks for the shout-out Ben.

We have some test models in the new glTF Sample Assets repo, which is meant to replace glTF Sample Models (once we get the kinks worked out).

- [AnisotropyBarnLamp](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp#anisotropy-barn-lamp) This has both circular and linear anisotropy, a normal map, and clearcoat. Lots of info in the readme.
- [AnisotropyRotationTest](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyRotationTest#anisotropy-rotation-test) testing rotation offsets.
- [AnisotropyStrengthTest](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyStrengthTest#anisotropy-strength-test) testing strength and roughness.

For additional normal maps, I noticed bump details don't light well when anisotropy is present. I showed an example of this in the [recent Khronos webinar](https://www.khronos.org/events/exploring-the-artistic-frontier-unleashing-creativity-in-3d-models-with-gltf-and-pbr) I did, here's the video https://www.youtube.com/watch?v=PyMgrV8BErY&t=1377s

**Comment by bhouston** [comment]
Amazing!  Of course you are on top of it @echadwick-artist , we just need to deprecate this repo because it is the duplicate repos that is causing the confusion.

**Comment by EricChadwick** [comment]
We could use some assistance in finalizing the automated checks in the new repo.

**Comment by bhouston** [comment]
I've created a pull request here for model-viewer render fidelity tests for these 3 models: https://github.com/google/model-viewer/pull/4493

**Comment by bhouston** [comment]
Closing as we've achieved our results!
