### ISSUE TITLE
Directory structure issues

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Models#396]
I think some of the recent merges have created problems.

```
$ ./generate-index.py
WARNING: no model files found for DirectionalLight
WARNING: no screenshot found for SheenDamask
WARNING: no screenshot found for XmpMetadataRoundedCube
```

**Comment by DrX3D** [comment]
I checked DirectionalLight and did find a model file. How/what/where is generate-index.py looking for model files?

SheenDamask and XmpMetadataRoundedCube do not have files called screenshot/screenshot.[jpg|png]. I'll push up the missing screenshots.

**Comment by DrX3D** [comment]
Screenshots and binary (for XMP...) files were created. Please review @emackey .

**Comment by emackey** [comment]
Looks good.  No warnings from `generate-index.py`.
