### ISSUE TITLE
Some 2.0 models are not compliant to the latest specification

### ISSUE THREAD

**Issue by lexchou** [KhronosGroup/glTF-Sample-Models#43]
According to the spec 2.0 here https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/glTF.schema.json, all objects under the root object should be an array, but I found only 3 sample models(BoomBox, Corset, Lantern) compliant to this spec.

Will the rest models update to the spec 2.0 or the spec 2.0 is still a draft?

**Comment by javagl** [comment]
The README.md currently carries a note:

> **Note:** These models are not yet updated to glTF 2.0!

(referring to the "Simple" models). The update of these models is in progress, as also discussed in the pull request https://github.com/KhronosGroup/glTF-Sample-Models/pull/37 

(For *some* of the models, the updated state is already contained in https://github.com/javagl/gltfTutorialModels/tree/2.0 , but they will be moved into *this* repository ASAP. Some other models (e.g. the ones involving custom techniques) are touching parts of the spec that are not yet finalized, but *most* of them should be doable by now)

**Comment by lexchou** [comment]
It's my fault that I didn't read the README.md carefully, and thank you for the response, I'll work on our own GLTF 2.0 importer based on the BoomBox, Corset,Lantern models.

**Comment by sbtron** [comment]
@lexchou there was an update to the spec around packing of metal roughness textures that was just made yesterday [#897](https://github.com/KhronosGroup/glTF/pull/897). These samples have not yet been updated to reflect that. will be posting an update soon.
