### ISSUE TITLE
AnimatedTriangle is not compatible with glTF2.0

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/glTF-Sample-Models#44]
This sample seems not compatible with glTF 2.0.
As far as I see, this model schema is more like glTF 1.0 not 2.0.

This is several points I noticed that it is not matching with glTF 2.0.

* `meshes` should be mesh
* `nodes` should be array of numbers
* `accessors` should be array

I guess there should be more wrong points.

**Comment by javagl** [comment]
Duplicate of https://github.com/KhronosGroup/glTF-Sample-Models/issues/43 . So I'll try to do these updates **today**, they seem to cause lots of confusion...

**Comment by kyasbal-1994** [comment]
@javagl I'm sorry to make duplicated issue. Thank you.

**Comment by javagl** [comment]
(Most of) the test models are going to be updated with https://github.com/KhronosGroup/glTF-Sample-Models/pull/45
