### ISSUE TITLE
Simple sample model for testing PBR

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/glTF-Sample-Models#47]
If there was simple model just for testing pbr like below, it would be great. 

![](http://project-asura.com/blog/wp-content/uploads/2016/02/UE4_Fig_5.png)

And it is very good for comparing 2 libraries supporting PBR.

**Comment by pjcozzi** [comment]
@mlimper do you know of a test model this simple?

@kyasbal-1994 keep an eye on https://github.com/KhronosGroup/glTF-Sample-Models for sample models

**Comment by pjcozzi** [comment]
> @kyasbal-1994 keep an eye on https://github.com/KhronosGroup/glTF-Sample-Models for sample models

Ah, sorry I thought I was in another repo!

**Comment by javagl** [comment]
A while ago, I started with this, and created something like https://github.com/javagl/gltfTestModels/tree/master/SimpleSpheres , for example. **BUT these models are still using glTF 1.0, and NOT glTF 2.0!**. This repo is mainly intended for personal use, to get a grip on glTF 2.0 and PBR, but of course, with the intention to have a set of "Simple (PBR) Test Models" eventually. 

Locally, I also started creating a "PBR Cube", showing the different features and maps that are involved in PBR. But @McNopper already created https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cube , which **is** an actual glTF 2.0 model - so I'd start with this.

**Comment by emackey** [comment]
I plan to submit some sample models as well, putting metal-rough PBR through its common use-cases.

**Comment by pjcozzi** [comment]
Thanks for the models in #50, @emackey!

**Comment by emackey** [comment]
@kyasbal-1994 let me know what you think:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres

**Comment by kyasbal-1994** [comment]
@emackey Awesome. I think this model make library contributors including me being able to debug PBR easily.  Thank you a lot!! 😸
