### ISSUE TITLE
Optimize and regenerate 1.0 sample models

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF-Sample-Models#5]
Go through and create all embedded/separate variants of each sample model, optimize them with glTF-pipeline to make them as small as possible, and make sure they render and pass validation.

- [ ] 2CylinderEngine (#4)
- [ ] Box (#6)
- [ ] BoxAnimated (#7)
- [ ] BoxSemantics
- [ ] BoxTextured
- [ ] BoxWithoutIndices
- [ ] BrainStem
- [ ] Buggy
- [ ] CesiumMan
- [ ] CesiumMilkTruck
- [ ] Duck
- [ ] GearboxAssy
- [ ] Monster
- [ ] ReciprocatingSaw
- [ ] RiggedFigure
- [ ] RiggedSimple
- [ ] VC

**Comment by lexaknyazev** [comment]
> make sure they render and pass validation

Please, keep in mind that 1.0 models won't pass validation, since validator supports only 1.1.

**Comment by pjcozzi** [comment]
@lasalvavida did you mean to name this 1.1?

**Comment by lasalvavida** [comment]
> @lasalvavida did you mean to name this 1.1?

No, this is for 1.0. There are a couple of issues (#2 and #3) with the 1.0 sample models so this is meant to be the last update to the 1.0 sample models before I do generation for 1.1. Many of them will also be substantially smaller after running through the pipeline.

**Comment by lasalvavida** [comment]
> Please, keep in mind that 1.0 models won't pass validation, since validator supports only 1.1.

Yup, but I think I've got a pretty good idea which errors can be safely ignored. You're double checking would be appreciated though.

**Comment by lasalvavida** [comment]
I also want to make sure that the 1.0 models are organized the same way that the 1.1 models are going to be.

**Comment by javagl** [comment]
(Side note: I'm curious whether this will have an effect on these boxes in the VC model that had been mentioned in https://github.com/KhronosGroup/glTF/issues/576 - these are still bugging me a bit, but admittedly, I also didn't check whether there might be something wrong in the renderer)
