### ISSUE TITLE
Add Missing Source Models

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF-Sample-Models#51]
Currently we have some glTF 2.0 models that have been graciously contributed that unfortunately we don't have source models for. This makes it hard to maintain this repo in general since these models have to be updated by hand when the schema changes, along with generation of the model variants. Adding these will also help me find and correct any issues with COLLADA2GLTF-2.0's PBR generation.

If you've contributed a glTF 2.0 model without a source model, I would really appreciate it (if possible) if you could open a PR contributing the source model as well, preferably in COLLADA format into the `sourceModels` directory.

The following don't have source models:
* [ ] AdvancedMaterial
* [ ] AnimatedCube
* [ ] AnimatedTriangle
* [x] BoomBox
* [ ] Cameras
* [x] Corset
* [ ] Cube
* [x] Lantern
* [x] MetalRoughSpheres
* [x] NormalTangentTest
* [ ] SciFiHelmet
* [ ] SimpleMaterial
* [ ] SimpleMeshes
* [ ] SimpleOpacity
* [ ] SimpleSkin
* [ ] SimpleTexture
* [ ] Suzanne
* [ ] Triangle
* [ ] TriangleWithoutIndices
* [ ] TwoSidedPlane

Again, thank you all for everything you're doing to help push glTF 2.0 along.

@pjcozzi 
@emackey 
@javagl 
@bghgary 
@McNopper

**Comment by javagl** [comment]
The models that are listed as ["Simple models for testing individual features" in the README](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#simple-models-for-testing-individual-features), namely

- [ ] AdvancedMaterial
- [ ] AnimatedTriangle
- [ ] Cameras
- [ ] SimpleMaterial
- [ ] SimpleMeshes
- [ ] SimpleOpacity
- [ ] SimpleSkin
- [ ] SimpleTexture
- [ ] Triangle
- [ ] TriangleWithoutIndices

are indeed created manually. They orginally had been created for the glTF tutorial, tweaking e.g. the order of the top level dictionaries/arrays to "group" them sensibly, and roughly match the descriptions in the tutorial. So there is no "source model" for those.

**Comment by bghgary** [comment]
@lasalvavida All of the models I added are sourced from FBX's with separate textures for each map specifically made for Unity's standard PBR materials. I can add these source files as well, but I'm not sure how useful they will be. Let me know if you want them anyways.

**Comment by lasalvavida** [comment]
@bghgary, if you could add them anyway, that would be terrific!

**Comment by emackey** [comment]
For MetalRoughSpheres and NormalTangentTest, I do have COLLADA models with geometry/normals/UVs, but all of my texturemap names were hand-edited into the glTF.  I notice that some of the other sample models seem to be using COLLADA's `profile_COMMON` with diffuse and specular channels, but my models need basecolor, occlusionRoughnessMetalness, and normal.  How can I produce a COLLADA model that contains an occlusionRoughnessMetalness map in it?

**Comment by lasalvavida** [comment]
My approach for this may not be perfect, but it seems to pretty accurately reflect the mapping in models for which I have both a COLLADA `profile_COMMON` and a glTF PBR variant.

Using MetalRoughSpheres as an example, our PBR material is:
```json
{
    "pbrMetallicRoughness": {
        "baseColorFactor": [
            1,
            1,
            1,
            1
        ],
        "baseColorTexture": {
            "index": 0
        },
        "metallicRoughnessTexture": {
            "index": 1
        }
    }
}
```

You can get this out of COLLADA2GLTF-2.0 with the following COLLADA `profile_COMMON`:
```xml
<profile_COMMON>
    <newparam sid="baseColorTexture-surface">
        <surface type="2D">
            <init_from>baseColorTexture-image</init_from>
            <format>A8R8G8B8</format>
        </surface>
    </newparam>
    <newparam sid="baseColorTexture-sampler">
        <sampler2D>
            <source>baseColorTexture-surface</source>
            <minfilter>LINEAR_MIPMAP_LINEAR</minfilter>
            <magfilter>LINEAR</magfilter>
        </sampler2D>
    </newparam>
    <technique sid="common">
        <phong>
            <diffuse>
                <texture texture="baseColorTexture-sampler" texcoord="Texture" />
            </diffuse>
        </phong>
    </technique>
</profile_COMMON>
```

And by specifying the `--metallicRoughnessTexture` flag on the command line pointing to your metallic roughness texture. If you include this texture as `${MODEL_NAME}_metallicRoughness.png` my python conversion script will pick it up for you automatically. Looking now, it looks like I forgot to include those in `sourceModels` when I did the move, so I'll have that fixed in the 2.0 PR shortly.

For NormalTangentTest, put occlusion in ambient and normal in bump.

**Comment by McNopper** [comment]
The assets from my side were done in Blender and exported to a proprietary asset format and finally exported again to glTF 2.0.
I suggest to provide the Blender files, as sooner or later we will have a Blender to glTF 2.0 exporter.

**Comment by lasalvavida** [comment]
@McNopper, adding the blender files would be ideal

**Comment by lilleyse** [comment]
> And by specifying the --metallicRoughnessTexture flag on the command line pointing to your metallic roughness texture.

It may be a good idea to separate metallic and roughness as inputs, and combine in the tool.

**Comment by emackey** [comment]
Note that a model can contain multiple materials, and each material can have its own roughnessMetallic texture, separate from other materials.

Maybe there could be a commandline flag to indicate that some other channel, such as the specular color channel, contains a reference to a roughnessMetallic texture (or even an occlusionRoughnessMetallic texture) instead of an actual specular map.  This way, each material could specify its own map.

**Comment by lasalvavida** [comment]
> a model can contain multiple materials

In the short term, my solution to this will probably be `--metallicRoughnessTexture[_index]` with the optional `index` being the `effect` index in `library_effects`.

**Comment by cx20** [comment]
@lasalvavida  The SmileFace.dae contains vertex color problems, I think that improvement is necessary.
This model has vertex colors all zero.
https://github.com/KhronosGroup/glTF-Sample-Models/blob/f442df2e47530fa5c3ab38279ab024ae776ace3f/sourceModels/SmilingFace/SmilingFace.dae#L107
@bghgary Do you know the correct data source for the model?

Related: https://github.com/mrdoob/three.js/issues/11264

**Comment by bghgary** [comment]
CC @sbtron

The source model, similar to the PBR models, started with an FBX. This particular model had a bug where 
the vertex colors were all zeroes. I think the root of this issue is that it was authored incorrectly.

**Comment by McNopper** [comment]
As soon as the glTF 2.0 Blender exporter has made some progress and major changes will not occur anymore, I will upload the Blender files depending on the provided PBR metal roughness cycles node:
https://github.com/KhronosGroup/glTF-Blender-Exporter

**Comment by emackey** [comment]
Closing this issue. Not every sample glTF model here will have some other "source" format that automatically converts exactly to the sample presented here.  Many of these samples test edge cases or experimental features using hand-crafted modifications.  Some of these glTF files are entirely hand-crafted in glTF from scratch (eg, SimpleSkin).
