### ISSUE TITLE
Some models contain an empty `animations` array

### ISSUE THREAD

**Issue by peteroupc** [KhronosGroup/glTF-Sample-Models#52]
Some of the sample models for glTF 2.0 contain an empty `animations` array (such as Suzanne, TwoSidedPlane, and Cube). Since the current schema doesn't allow the `animations` property to appear as an empty array, the `animations` property should be removed from the affected models.

**Comment by pjcozzi** [comment]
@lasalvavida can you make this change?

**Comment by pjcozzi** [comment]
Thanks @peteroupc @lasalvavida!

**Comment by peteroupc** [comment]
This issue originally dealt with the `animation` array, but in fact this points to a broader issue: some models contain empty arrays where they're optional in the schema.  For example, this broader issue persists in the AnimatedCube model with the `children` property, and possibly in other models with that or other properties.

**Comment by lasalvavida** [comment]
@McNopper, for your reference. It sounds like this may be an issue in your exporter

**Comment by UX3D-nopper** [comment]
These models were exported directly from my Vulkan examples. I will check this. Thx.

In the Blender glTF 2.0 exporter, this should not appear.

**Comment by McNopper** [comment]
Just checked, it is my "Vulkan" to glTF 2.0 exporter. Currently revisiting the whole code anyway.

The Blender glTF 2.0 exporter is doing it correct.
