### ISSUE TITLE
Some 2.0 sample models report their version as 1.1

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#53]
For example: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Triangle/glTF/Triangle.gltf#L65

CC @javagl

**Comment by peteroupc** [comment]
On a similar note, some glTF 1.0 models report a version `1.0.1`, for example, the Avocado model.

**Comment by cx20** [comment]
Several version problems seem to be solved in the following PR.
https://github.com/KhronosGroup/glTF-Sample-Models/pull/45

|Model Name              |Current|PR  |
|:-----------------------|:-----:|:--:|
|Triangle Without Indices|1.1    |2.0 |
|Triangle                |1.1    |2.0 |
|Animated Triangle       |1.1    |2.0 |
|Simple Material         |1.1    |2.0 |
|Simple Meshes           |1.1    |2.0 |
|Advanced Material       |1.1    |1.1 |
|Simple Opacity          |1.1    |1.1 |
|Simple Texture          |1.1    |2.0.0|
|Cameras                 |1.1    |2.0 |
|Simple Skin             |1.1    |1.1 |

I think that `2.0.0` of Simple Texture is incorrect.

**Comment by javagl** [comment]
@pjcozzi As cx20 mentioned, the #45 update fixes most of them. The ones that still carry a 1.1 or 2.0.0 after this pull request are still to be updated. 

<sub>(Maybe I have to swallow my pride of being able to *render* these test models with my own implementation, and just update them according to the spec. Right now, I cannot foresee how long it will take until I have my own PBR implementation working. It's challenging, for sure.)</sub>

**Comment by pjcozzi** [comment]
@javagl there are drag-and-drop glTF 2.0 loaders for three.js and BabylonJS that you could test updated models with.  If you are up for it, I think it would help the ecosystem to have the sample models updated even if all our renderers aren't updated yet.

**Comment by javagl** [comment]
The point is: When a model does not work as expected, I don't know who to blame: The model or the renderer. But with *two* renderers, we have a committee ;-) so I'll tackle this ASAP

**Comment by emackey** [comment]
> there are drag-and-drop glTF 2.0 loaders for three.js and BabylonJS

Does someone have the links to these two drag-and-drop loaders handy?

**Comment by bghgary** [comment]
https://gltf-viewer.donmccurdy.com/
https://sandbox.babylonjs.com/

**Comment by cx20** [comment]
@pjcozzi The latest PR https://github.com/KhronosGroup/glTF-Sample-Models/pull/45 is as follows.

|Model Name              |Current|PR     |
|:-----------------------|:-----:|:-----:|
|Triangle Without Indices|1.1    |2.0    |
|Triangle                |1.1    |2.0    |
|Animated Triangle       |1.1    |2.0    |
|Simple Material         |1.1    |removed|
|Simple Meshes           |1.1    |2.0    |
|Advanced Material       |1.1    |removed|
|Simple Opacity          |1.1    |removed|
|Simple Texture          |1.1    |removed|
|Cameras                 |1.1    |2.0    |
|Simple Skin             |1.1    |removed|

Since there is confusion if there is a model of glTF 1.1 in the 2.0 hierarchy, I think that it is good to merge PR once.

CC @javagl

**Comment by pjcozzi** [comment]
Thanks @cx20!  Is it OK to close this now?

**Comment by peteroupc** [comment]
There's still one thing I want to clear up: " some glTF 1.0 models report a version 1.0.1, for example, the Avocado model, where as far as I know, a third number in the version string is not specified (as opposed to major and minor version)."

**Comment by cx20** [comment]
@pjcozzi I think that Issue can be closed. All versions of the glTF 2.0 model are "2.0" now.
@peteroupc I think that it is better to make another Issue that some of the models of glTF 1.0 are "1.0.1".

**Comment by pjcozzi** [comment]
@peteroupc those "1.0.1" models should report "1.0."  I submitted #72.  A fix would be welcome if you are able to contribute.

**Comment by pjcozzi** [comment]
Ah, I see #71.
