### ISSUE TITLE
occlusionMetallicRoughness

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF-Sample-Models#54]
Hi,

I see the gltf2 corset sample model has its occlusion/metallic/roughness textures packed into the one texture:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Corset/glTF/Corset_occlusionRoughnessMetallic.png

But which texture channels go where? Is it R=occlusion, G=metallic, B=roughness? Is this hardcoded in or docced anywhere?

And will there be a cheat sheet for gltf2?

Bye!
Mark

**Comment by donmccurdy** [comment]
Hi @blitz-research — glTF uses the same packing order as UE4:

| channel | texture |
|---|----|
| red | occlusion |
| green | roughness |
| blue | metallic |

This is [described in the schema](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/material.pbrMetallicRoughness.schema.json#L45), but I'm not sure it's made it into the human-readable spec yet.

There is discussion in a [github issue with much more detail here](https://github.com/KhronosGroup/glTF/issues/857). Here is the [relevant UE4 documentation](https://support.allegorithmic.com/documentation/display/SPDOC/Unreal+Engine+4); those are the export settings you would use in Substance Painter, for example.

**Comment by pjcozzi** [comment]
> And will there be a cheat sheet for gltf2?

I hope so!  @javagl is the creator of the 1.0 reference.

**Comment by javagl** [comment]
>> And will there be a cheat sheet for gltf2?
>
> I hope so! @javagl is the creator of the 1.0 reference.

The PBR is a big thing. There certainly will be an update for the overview - hopefully soon, but don't hold you breath.

**Comment by blitz-research** [comment]
Thanks Don, just what I needed. All the info is indeed there somewhere,
it's just a bit hard to find sometimes!

**Comment by emackey** [comment]
OK to close this?

**Comment by blitz-research** [comment]
Fine with me.
