### ISSUE TITLE
Simple test models and "Unit Test" models

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Sample-Models#57]
Originally, the "Simple Test Models" (as they are listed in the [first table of the current README](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/README.md) ) had been created for the Tutorial. But then they have been added here (as requested in https://github.com/KhronosGroup/glTF-Sample-Models/issues/16 ). The intention behind adding these models here was to have a set of models that people could use to develop their loaders incrementally: Starting with the simplest possible model, they could add support for one feature, and test this feature, using "the simplest possible model that contains *exactly* this feature".

So in some sense, the role of these "Simple" models is similar to that of the "Unit Test" models, that may be added here soon (as discussed offline). And there are some technical similarities, in the sense that neither the "Simple" models nor the "Unit Test" models have a "*Source*" model (as requested in https://github.com/KhronosGroup/glTF-Sample-Models/issues/51 )

Are there any preferences about the structure and organization of these models? What is the intented structure and presentation of the "Unit Test" models? (Regarding the directory layout, naming, description etc...)

(A side note: Some of the "Unit Test" Models will probably be broken - *intentionally*! - in the sense that they have a structure that is invalid and *should* cause loaders to bail out. For example, for testing the Validator: There will probably be *one* model for *each* possible warning/error message, to make sure that the Validator actually detects the respective error. These "invalid" models should be clearly marked as such.)

@pjcozzi @lexaknyazev (+ please add other mentions as appropriate - I'm not sure who committed to creating the Unit Test Models...)

**Comment by pjcozzi** [comment]
+ @sbtron, the mastermind for the unit test models.

**Comment by sbtron** [comment]
Here is a tool we started writing to automate the process of generating these models. https://github.com/bghgary/glTF-Asset-Generator 

Will post some samples once they are in a decent testable state.

**Comment by javagl** [comment]
As an (internal, not yet publicly available) part of https://github.com/javagl/JglTF I also created some utility classes for this. Until now, these focus on the `buffer`/`bufferView`/`accessor` structure. They allow assembling these structures from some raw arrays that contain indices/positions/normals/etc. Eventually, these structures can be visualized, and the visualization may be saved as SVG or PNG, as shown in the [data layout images](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle#data-layout) that are already part of some models. Maybe this will be part of the jgltf-browser, or a small standalone tool in the future. (I'm still busy with the 2.0 branch right now)

**Comment by kcoley** [comment]
> Here is a tool we started writing to automate the process of generating these models. https://github.com/bghgary/glTF-Asset-Generator

> Will post some samples once they are in a decent testable state.
 
This is an initial pass of generating these test models.  It is still work in progress so any feedback is appreciated.  We have currently generated test models for Materials, Textures and Samplers.  These are all positive tests.

**Comment by emackey** [comment]
@javagl I think this can be closed now.

**Comment by javagl** [comment]
Sure, the current sample models and asset generator cover this pretty well, and more models can be added on demand.
