### ISSUE TITLE
Some glTF 2.0 models readme.md is not placed

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/glTF-Sample-Models#62]
The following glTF 2.0 models don't have readme.md:

- [ ] 2CylinderEngine
- [ ] Avocado
- [ ] BarramundiFish
- [ ] Box
- [ ] BoxAnimated
- [ ] BoxTextured
- [ ] BrainStem
- [ ] Buggy
- [ ] CesiumMan
- [ ] CesiumMilkTruck
- [ ] Duck
- [ ] GearboxAssy
- [ ] Monster
- [ ] ReciprocatingSaw
- [ ] RiggedFigure
- [ ] RiggedSimple
- [ ] SmilingFace
- [ ] VC
- [ ] WalkingLady

I think that I forgot to copy from 1.0 when I regenerated.

**Comment by pjcozzi** [comment]
@cx20 would you be able to copy the 1.0 READMEs for these?

**Comment by cx20** [comment]
I added the following PR.
https://github.com/KhronosGroup/glTF-Sample-Models/pull/65

**Comment by pjcozzi** [comment]
Thanks @cx20!
