### ISSUE TITLE
Floating point precision of accessor.min/max

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Models#63]
As of 2.0, glTF spec has [explicit requirement](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/accessor.schema.json#L104) about JSON-stored `accessor.min/max` floating-point values:
>  When `componentType` is `5126` (FLOAT) each array value must be stored as double-precision JSON number with numerical value which is equal to buffer-stored single-precision value to avoid extra runtime conversions.

Currently, most models don't follow this.

**collada2gltf** (or just rapidjson) uses a bit different conversion process than JS:
```
/2CylinderEngine/glTF/2CylinderEngine.gltf#/accessors/2/min

Single-precision bytes (as in buffer): [0x38, 0xE5, 0x13, 0xC2]

ECMA Script: -36.973846435546875
Double-precision bytes: [0x00, 0x00, 0x00, 0x00, 0xA7, 0x7C, 0x42, 0xC0]

JSON-stored: -36.97384643554688
Double-precision bytes: [0x01, 0x00, 0x00, 0x00, 0xA7, 0x7C, 0x42, 0xC0]
```

**Unity Exporter** truncates numbers so they are equal in single-precision only
```
/Lantern/glTF/Lantern.gltf#/accessors/0/min

Single-precision bytes (as in buffer): [0xE0, 0xE8, 0x2F, 0x3C]

ECMA Script: 0.010736674070358276
Double-precision bytes: [0x00, 0x00, 0x00, 0x00, 0x1C, 0xFD, 0x85, 0x3F]

JSON-stored: 0.0107366741
Double-precision bytes: [0x3A, 0xBB, 0x04, 0x01, 0x1C, 0xFD, 0x85, 0x3F]
```

CC @pjcozzi @lasalvavida @bghgary @UX3D-nopper

**Comment by lasalvavida** [comment]
Okay; I will use single precision for computing mins and maxes so that the values match as best they can.

Most are probably aware of this already, but just in case, the single precision bytes and double precision floating points bytes likely won't match because the byte layout for each data type is different. This mostly just means not to expect the double precision bytes to be the single one with all zeros at the end.

__Single-precision__
![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Float_example.svg/590px-Float_example.svg.png)

__Double-precision__
![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/IEEE_754_Double_Floating_Point_Format.svg/618px-IEEE_754_Double_Floating_Point_Format.svg.png)

**Comment by lexaknyazev** [comment]
If precisely following this requirement is too difficult, we could think of possible alternative: state that `accessor.min/max` values MUST be treated as single-precision decimals. In such case, JSON-stored decimals could be shorter (as Unity exporter does already).

This would put some burden on clients, because JSON parsers usually output doubles. For JS it will be like:

**ES5:**
```javascript
var _float = new Float32Array(1);
function getSinglePrecision(value) {
  return _float[0] = value, _float[0];
}
var single = getSinglePrecision(double);
```
**ES6:**
```javascript
var single = Math.fround(double);
```

**Comment by bghgary** [comment]
>  stored as double-precision JSON number with numerical value which is equal to buffer-stored single-precision value to avoid extra runtime conversions

I don't understand this part. What is extra runtime conversion are we avoiding? Besides difference in length of text and parsing time in the JSON, does it matter whether the min/max number is single precision or double precision?

**Comment by lexaknyazev** [comment]
> What is extra runtime conversion are we avoiding?

Runtimes without notion of single-precision (such as JS) will get different values from binary buffer and JSON. 

See example of getting "intended" max value in JS in the comment above.

**Comment by bghgary** [comment]
> Runtimes without notion of single-precision (such as JS) will get different values from binary buffer and JSON.

I agree raw bytes will be different, but comparing floating-point values almost always involves an epsilon anyways, so I don't see a problem. What do we expect runtimes to do with the min/max values?

**Comment by lasalvavida** [comment]
It looks like what you're seeing is a byproduct of a bug in rapidjson's double->string conversion. The values are correct in memory, but the written string is incorrect.

I do think this requirement is a little too strict. I would advocate requiring min and max to only bound the data not necessarily having strict equality with the actual min and max.

**Comment by lasalvavida** [comment]
I opened https://github.com/miloyip/rapidjson/issues/954 for this issue

**Comment by lexaknyazev** [comment]
> I agree raw bytes will be different, but comparing floating-point values almost always involves an epsilon anyways, so I don't see a problem.

The goal is to not have different representations of the same value. I find it odd that the asset may not agree with itself on the min/max, since there could be cases when binary-stored float32 value is actually less than JSON-stored `min` parsed as double. E.g., `0.0107366741` (from the first post) doesn't bound accessor's data.

However, given that ES6 has an idiomatic way of getting proper float32 values (`Math.fround`), I think we should mandate only single-precision equality (no epsilon required). 

Models produced by collada2gltf and Unity Exporter already satisfy this.

**Comment by aaronfranke** [comment]
> As of 2.0, glTF spec has explicit requirement 

That link doesn't work anymore. For the record, here's an updated link: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/accessor.schema.json
