### ISSUE TITLE
Most 2.0 sample still have byteStride on accessor instead of bufferView

### ISSUE THREAD

**Issue by bwasty** [KhronosGroup/glTF-Sample-Models#68]
The `byteStride` property has moved from `accessor` to `bufferView` (see https://github.com/KhronosGroup/glTF/issues/827, https://github.com/KhronosGroup/glTF/issues/605),
but as far as I see all samples that specify `byteStride` explicity still have it on `accessor`.

**Comment by lexaknyazev** [comment]
Most of them were fixed with a6f9c0884866539da8e9b7f7a3acab68fb6a13aa.

**Comment by lexaknyazev** [comment]
Only two models remain unfixed (#70).
