### ISSUE TITLE
MetalRoughSpheres and NormalTangentTest are outdated

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Models#70]
@emackey 
Could you regenerate [MetalRoughSpheres](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres) and [NormalTangentTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) with the latest collada2gltf version?

**Comment by cx20** [comment]
BTW, MetalRoughSpheres and NormalTangentTest are not listed in the model list README.md. I think that it is better to add it.
