### ISSUE TITLE
Some glTF 1.0 models report "1.0.1"

### ISSUE THREAD

**Issue by peteroupc** [KhronosGroup/glTF-Sample-Models#71]
Some glTF 1.0 models report a version 1.0.1, for example, the Avocado model, where as far as I know--
- a third number in the version string is not specified (as opposed to major and minor version), and
- there has been no draft or ratified glTF specification with that version number.

**Comment by cx20** [comment]
Version "1.0.1" seems to be set by collada2gltf.
I tried examining the generator version of the glTF 1.0 model.

|generator   |GIT_SHA1                                |commit date |version|
|:----------:|:--------------------------------------:|:----------:|:-----:|
|collada2gltf|027f74366341d569dea42e9a68b7104cc3892054|2016/04/20 |1.0    |
|collada2gltf|774bd4fe67703fbf60f9c02f3ba79632f246e9b6|2016/04/26 |1.0    |
|collada2gltf|6779c094d694e951beeb1012d03d4faa1edb0ddf|2016/11/02 |1.0.1  |
|collada2gltf|f8f6279915175e9d2cc525531660ac439c114fac|2016/12/01 |1.0.1  |

Looking at the commit history seems that "1.0" -> "1.0.1" has been changed on 2016/08/02.
https://github.com/KhronosGroup/COLLADA2GLTF/commit/9d9e88f4a1ced7618edefb186ab00c226c61c121

@lasalvavida Is this a correct specification?

**Comment by cx20** [comment]
I confirmed that version `1.0.1` is set on the following 4 models.

|Model Name     |Generator   |GIT_SHA1                                |Version|
|:--------------|:-----------|:--------------------------------------:|:-----:|
|Avocado        |collada2gltf|f8f6279915175e9d2cc525531660ac439c114fac|1.0.1  |
|BarramundiFish |collada2gltf|f8f6279915175e9d2cc525531660ac439c114fac|1.0.1  |
|SmilingFace    |collada2gltf|f8f6279915175e9d2cc525531660ac439c114fac|1.0.1  |
|WalkingLady    |collada2gltf|6779c094d694e951beeb1012d03d4faa1edb0ddf|1.0.1  |

Until a new version of COLLADA2GLTF is created, I'd like to fix the version of the glTF 1.0 model by hand from `1.0.1` to `1.0`.

COLLADA2GLTF is creating a new version for glTF 2.0, however it seems that it will take time to develop the function of glTF 1.0 backport. (https://github.com/KhronosGroup/COLLADA2GLTF/pull/83)

/cc @sbtron @deltakosh

**Comment by emackey** [comment]
I think, given the history, any remaining glTF 1.0 implementations should be tolerant of `1.0.1` and treat it as `1.0`.  The 2.0 spec is much tighter about versioning.
