### ISSUE TITLE
Update SpecGloss models from COLLADA2GLTF

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Models#74]
- Schema syntax bug: https://github.com/KhronosGroup/COLLADA2GLTF/issues/43.

- Models without textures (`2CylinderEngine`, `Box`, `BoxAnimated`, `BrainStem`, `Buggy`, `GearboxAssy`, `ReciprocatingSaw`, `RiggedFigure`, `RiggedSimple`, `WalkingLady`) don't have SpecGloss material at all despite having `glTF-pbrSpecularGlossiness` directory.

- All SpecGloss models from COLLADA2GLTF use base64-encoded buffers and images.

**Comment by emackey** [comment]
We're deprecating the old SpecGloss extension in favor of `KHR_materials_specular`.

As far as I know, all of the old SpecGloss samples were merely converted from metal/rough sources, or old-fashioned non-PBR diffuse/specular sources.  None of them were taking advantage of the PBR-enabled spec/gloss workflow beyond what metal/rough can do.  There is a newer Specular Test model that tests `KHR_materials_specular`.

Perhaps all of the `glTF-pbrSpecularGlossiness` folders should be removed.
