### ISSUE TITLE
Preview glTF in GitHub

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#75]
It would be awesome to be able to click on a .glb or .gltf file in GitHub and then view it like [STL](https://github.com/blog/1465-stl-file-viewing).

Is it possible to do this as a GitHub plugin?  Or would GitHub have to implement this?

It would be even more amazing to be able to switch different engines for testing just like the VSCode plugin, https://github.com/AnalyticalGraphicsInc/gltf-vscode

Could be great to have this as the preview for CI, #26.

Contributions welcome, I only wish I had the time to do this myself. :stuck_out_tongue_winking_eye:

**Comment by donmccurdy** [comment]
I sent a note to GitHub through their contact form. Not sure how likely they are to reply, but since they're using three.js already, maybe we'll get lucky.

If not, I'm reasonably confident this could be implemented as a Chrome Extension using http://rawgit.com/ as the CDN, which should preserve relative URL structures. But I haven't got much bandwidth to implement something like that myself right now, unfortunately.

**Comment by donmccurdy** [comment]
In the meantime, here's a bookmarklet:

```
javascript:(function() {
  var path = (document.querySelector('#raw-url') || location).pathname;
  var url = 'https://raw.githubusercontent.com' + path.replace('/raw/', '/');
  window.open('https://gltf-viewer.donmccurdy.com/#model=' + url, '_blank');
}());
```

![52dd8ada-cda0-4cc2-a86d-89177793ebdd-26142-00001ab0b915f4cf](https://cloud.githubusercontent.com/assets/1848368/26615809/9b078bb6-457e-11e7-9634-81381f15beda.gif)

**Comment by pjcozzi** [comment]
Ah, very cool, @donmccurdy!  Let us know if you hear from GitHub.

**Comment by donmccurdy** [comment]
I got stock reply from GitHub customer service. From this thread on twitter, it sounds like they aren't adding new formats these days: https://twitter.com/mrdoob/status/869789944104996864 :/

**Comment by pjcozzi** [comment]
Thanks for the update, perhaps they'll reconsider as glTF gains more traction.

**Comment by pjcozzi** [comment]
@donmccurdy do you think it is worth putting this in a simple GitHub repo or blog post tutorial so we can link to it from the main README.md?  This just came in handy again for me!

**Comment by donmccurdy** [comment]
I've submitted a browser extension to the Chrome and Firefox stores. Assuming it's approved, we can link to those.

![preview](https://user-images.githubusercontent.com/1848368/28243354-21761e0e-697b-11e7-8965-a093cb0031b4.png)

**Comment by pjcozzi** [comment]
Very cool, thanks @donmccurdy!  Is this only glTF 2.0?  With 1.0 sample models, I get:
```
Uncaught Error: GLTF2Loader: Legacy binary file detected. Use GLTFLoader instead.
    at new GLTFBinaryExtension (bundle.js:1087)
    at GLTF2Loader.parse (bundle.js:645)
    at bundle.js:618
    at XMLHttpRequest.<anonymous> (bundle.js:51438)
```

**Comment by donmccurdy** [comment]
Correct — The browser extension doesn't care about version, but I only have glTF 2.0 support in the viewer. I do plan to add a more user-friendly error, along the lines of "Older versions of glTF are unsupported", on the page rather than in the JS console.

**Comment by pjcozzi** [comment]
Gotcha, sounds good!

**Comment by emackey** [comment]
@donmccurdy Is the source for the extension itself available on GitHub?

**Comment by donmccurdy** [comment]
@emackey just published: https://github.com/donmccurdy/glTF-Browser-Extension

**Comment by pjcozzi** [comment]
This is really fantastic, thanks again @donmccurdy!

Should we close this or do you want to keep this open as a reminder that it would be cool for GitHub to do this as a core feature?

**Comment by donmccurdy** [comment]
> Should we close this or do you want to keep this open as a reminder that it would be cool for GitHub to do this as a core feature?

Fine with me either way; it might be nice to keep it open as a place for others to upvote the first post and show interest.

**Comment by pjcozzi** [comment]
Will keep it open.

**Comment by DrX3D** [comment]
Untouched for 6+ years. The current repo (glTF-Sample-Asset) does display in Sample Viewer. Not the same as the original request, but perhaps that is sufficient for this repo & issue.

**Comment by emackey** [comment]
Agreed. We can't control what GitHub chooses to do with glTF files natively, but we have the workarounds mentioned above.
