### ISSUE TITLE
Water bottle is missing

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Sample-Models#79]
The sample glTF water bottle is featured in the last set of slides of the [glTF launch presentation](https://www.khronos.org/assets/uploads/apis/glTF-20-Launch_Jun17.pdf), and is present in the [PBR reference shader repo](https://github.com/KhronosGroup/glTF-WebGL-PBR/tree/fa1ee34d00748e43ea42039191000041b2d6a6bc/models/WaterBottle) and Microsoft's [test BabylonJS repo](https://github.com/sbtron/BabylonJS-glTFLoader/tree/e7b65123a5247989f79b3ad69469307a368e4fa6/src/models/2.0/png/WaterBottle).  Here's a [live demo](https://emackey.github.io/BabylonJS-glTFLoader/?model=WaterBottle&pointLight=true).

That water bottle is missing from this sample model repo.  Can it be added?

/cc @sbtron @bghgary

**Comment by bghgary** [comment]
Yes, the plan is to add it. I need to get one of our artist to update the specular-glossiness textures so that the text is not garbled from the automatic conversion.
