### ISSUE TITLE
Boom Box model with single buffer

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/glTF-Sample-Models#85]
Hello. My renderer at now not support multiply buffers, only single (but support accessors). How I can get Boom Box model with unified buffer (unified bufferView)? 
Also, only indices support separate buffers.

**Comment by lexaknyazev** [comment]
@capitalknew 
I assume that "unified buffer (unified bufferView)" means using only one bufferView for all vertex attributes. Is it correct? Exact layout depends heavily on tool used to produce an asset. 

E.g., Unity exporter (used for Avocado, BarramundiFish, BoomBox, Corset, and Lantern) puts each attribute into its own bufferView.

**Comment by capitalknew** [comment]
I mean that accessor have accesses to regions in bufferView (general stride 12, vertex offset is 0 or 3, texcoord +2 offset).

**Comment by capitalknew** [comment]
It possible to re-export glTF (i.e. restructure)?

**Comment by lexaknyazev** [comment]
Such functionality may become available as a part of
https://github.com/AnalyticalGraphicsInc/gltf-pipeline

CC @pjcozzi

**Comment by capitalknew** [comment]
I want this model today, need testing my PBR.

**Comment by emackey** [comment]
@capitalknew I think the `byteStride` property was moved to `bufferViews`.  The latest version of the Duck model, for example, uses multiple `bufferViews` with different strides, and can't be trivially combined.

**Comment by capitalknew** [comment]
I have support of BufferViews (if two BufferViews i.e. data and indices for every node). When more than one data BufferViews per node, I have no support.

**Comment by capitalknew** [comment]
I remedy loader for better striding. So I successfully loaded some models.

**Comment by pjcozzi** [comment]
> Such functionality may become available as a part of
https://github.com/AnalyticalGraphicsInc/gltf-pipeline

Yes, see https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/1.  Contributions always welcome!
