### ISSUE TITLE
Sponza and Chess PBR models?

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Sample-Models#87]
Hello. Where and how I can get glTF 2.0 versions of sponza and chess models/scenes?

**Comment by pjcozzi** [comment]
@capitalknew perhaps import into Blender then export with [glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter)?

[obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf) and [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF) are not at 100% 2.0 support yet.

**Comment by emackey** [comment]
Sponza is included in this repo now.
