### ISSUE TITLE
multi nodes, inv xy quaternion sample model?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#89]
@Fabrice3D this looks like a nice test model that would be useful to the community if you want to contribute it to this repo?

![image](https://user-images.githubusercontent.com/782098/27636928-cf1f9772-5bdb-11e7-848d-6c2b510fd753.png)

https://sketchfab.com/models/7f47f3fc84174a8bbe0e375f6a21e6a5

**Comment by Fabrice3D** [comment]
No sorry, I can't to this to the community, this one is really too ugly!
Instead, Id be happy to contribute and make a new one similar, 
having the necessary elements to test TRS keyframes
but looking bits better and less confusing visually to compare with own imports or exports.
Now that my import/edit/export chain works, that should not take long.

**Comment by pjcozzi** [comment]
Sounds great @Fabrice3D!

**Comment by DrX3D** [comment]
Will be closing this issue within a month @pjcozzi @Fabrice3D . If you wish to contribute a model please create a PR for [glTF-Sample-Assets repo](https://github.com/KhronosGroup/glTF-Sample-Assets).

**Comment by DrX3D** [comment]
Closed because there are no recent requests
