### ISSUE TITLE
Cessium man rendering upside down?

### ISSUE THREAD

**Issue by memmottse** [KhronosGroup/glTF-Sample-Models#90]
Hello, I'm sure this is an issue on my end rather then the model end, but I thought I'd post just in case someone can point me to a theory.  On a 2.0 model loader I'm implementing, both the monster and the Cessium man are loading upside down for me.   If I pretend their matrix is row major instead of column major they load in fine.   I haven't seen this issue on any of the web based sample loaders I've been able to track down, So it's likely something I've doing incorrectly. 
(I'm new to gitHub, so if there is a better place to post a question like this then to create an issue, please let me know)
Thanks!

**Comment by lexaknyazev** [comment]
> On a 2.0 model loader I'm implementing, both the monster and the Cessium man are loading upside down for me.

Does this issue affect only those two models, i.e., are there any other models with same behavior? (Btw, those models contain skins, so the issue could be related to it.)

**Comment by memmottse** [comment]
I haven't implemented skinning or animation yet, so that could be the problem.  
But as far as I can tell I'm seeing it on Monster, Cessium man, textured box, and rigged figure.
I thought I was reading the matrix in incorrectly, but it works for the milk truck tires.
I'll finish implementing skinning and see what it looks like, but the textured box being upside down means I'm likely doing something incorrect elsewhere.
Thanks.

**Comment by jayid** [comment]
[https://www.youtube.com/watch?v=R5ZTbl2-BDU&feature=youtu.be](url)

I am working on gltf2.0 viewer with c++ . 
somehow cesium man looks like this in my viewer.
horizontal plane is xz plane. vertical axis is y.
so, I think the model is not upside down..   
but, as you can see in that link, animation looks strange !!
I dont know why.

**Comment by memmottse** [comment]
I finally got a chance to implement skinning, and I'm strangely still seeing the issue where all the skinned samples are rendering upside down for me.   I'm sure this is a local issue though, so I'm going to close the issue.
